force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Account_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Architect</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Bidder</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Building Contractor</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Building Owner</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Consultant</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Further Participants</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>General Constructor</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Operating Firm</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Operator</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Planer</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Planer and Engineers</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Project Controller</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Project Developer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Property Surveillance</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Tenant</label>
    </customValue>
    <masterLabel>Account Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SHRProjectAccountRelationTriggerHandler.cls
/**
 * Handler class detekt changes and routes to the business logic handlers
 * and executes dml operations.
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-09  isabella.moos@accenture.com     creation
 */
public with sharing class SHRProjectAccountRelationTriggerHandler extends UTLTriggerHandler  {
    public String CLASSNAME = String.valueOf(this).substring(0, String.valueOf(this).indexOf(':'));

    private DUPProjectAccountRelationHandler dupPARHandler = new DUPProjectAccountRelationHandler();

    private List<Project_Account_Relation__c> newPAR;
    private Map<Id, Project_Account_Relation__c> oldPARsByIds;
    private Map<Id, Project_Account_Relation__c> newPARsByIds;

    Map<Id, Project_Account_Relation__c> oldPARMap = new Map<Id, Project_Account_Relation__c>();
    Map<Id, Project_Account_Relation__c> newPARMap = new Map<Id, Project_Account_Relation__c>();

    public SHRProjectAccountRelationTriggerHandler() {
        this.oldPARsByIds = (Map<Id, Project_Account_Relation__c>) Trigger.oldMap;
        this.newPARsByIds = (Map<Id, Project_Account_Relation__c>) Trigger.newMap;
    }

    /**
     * Collecting inserted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterInsert
     */
    public override void afterInsert() {
        // Handle record update
        for (Id parId : this.newPARsByIds.keySet()) {
            Project_Account_Relation__c newPAR = this.newPARsByIds.get(parId);

            this.newPARMap.put(newPAR.Id, newPAR);
        }
        // handle if related Account Name change occured
        if (!newPARMap.isEmpty()) {
            this.dupPARHandler
                .addNewPARs(this.newPARsByIds)
                .executeJob(DUPProjectAccountRelationHandler.JobContext.ON_INSERT);
        }
    }

    /**
     * Collecting changed records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterUpdate
     */
    public override void afterUpdate() {
        // Handle record update
        for (Id parId : this.newPARsByIds.keySet()) {
            Project_Account_Relation__c oldPAR = this.oldPARsByIds.get(parId);
            Project_Account_Relation__c newPAR = this.newPARsByIds.get(parId);

            if (oldPAR.Account__c != newPAR.Account__c || 
            oldPAR.Account_Role__c != newPAR.Account_Role__c ||
            oldPAR.Project__c != newPAR.Project__c) {
                oldPARMap.put(oldPAR.Id, oldPAR);
                newPARMap.put(newPAR.Id, newPAR);
            }
        }
        // handle if related Account Name change occured
        if (! newPARMap.isEmpty() && 
        ! oldPARMap.isEmpty()) {
            this.dupPARHandler
                .addOldPARs(this.oldPARsByIds)
                .addNewPARs(this.newPARsByIds)
                .executeJob(DUPProjectAccountRelationHandler.JobContext.ON_UPDATE);
        }
    }

    /**
     * Collecting deleted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterDelete
     */
    public override void afterDelete() {
        // Handle record deletion
        for (Id parId : this.oldPARsByIds.keySet()) {
            Project_Account_Relation__c oldPAR = this.oldPARsByIds.get(parId);

            this.oldPARMap.put(oldPAR.Id, oldPAR);
        }
        // handle if related Account Name change occured
        if (! oldPARMap.isEmpty()) {
            this.dupPARHandler
                .addOldPARs(this.oldPARsByIds)
                .executeJob(DUPProjectAccountRelationHandler.JobContext.ON_DELETE);
        }
    }

    /**
     * Collecting deleted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterUndelete
     */
    public override void afterUndelete() {
        // Handle record deletion
        for (Id parId : this.newPARsByIds.keySet()) {
            Project_Account_Relation__c newPAR = this.newPARsByIds.get(parId);

            this.newPARMap.put(newPAR.Id, newPAR);
        }
        // handle if related Account Name change occured
        if (! newPARMap.isEmpty()) {
            this.dupPARHandler
                .addNewPARs(this.newPARsByIds)
                .executeJob(DUPProjectAccountRelationHandler.JobContext.ON_UNDELETE);
        }
    }
}