force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/iBau_ID__c.field-meta.xml
<CustomField>
    <fullName>iBau_ID__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-647. Stores the second available ibau-ID for later purposes.</description>
    <label>iBau ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BISBackLinkGeneratorTest.cls
/**
 * SF-854 Feld "ibau Rückverlinkung"
 *
 * BISBackLinkGeneratorTest
 *
 * @author Daniel Gette
 *
 * @version 14.02.2022 creation
 */

@IsTest
private class BISBackLinkGeneratorTest {

    private static Project__c createTestData(){
        Project__c project = new Project__c();
        project.Name = 'Test Project';

        project.Project_Address__CountryCode__s = 'DE';
        project.Project_Address__City__s = 'TestCity';
        project.Project_Address__PostalCode__s = '55555';
        project.Project_Address__Street__s = 'Test Street';

        return project;
    }

    @IsTest
    static void testLinkGenerationPositive() {
        Project__c project = createTestData();
        project.iBau_ID__c = '12345';
        insert project;

        String url = BISBackLinkGenerator.generateLinkForProject(project.Id);
        System.assert(url.contains(project.iBau_ID__c));
    }

    @IsTest
    static void testLinkGenerationNegativ() {
        Project__c project = createTestData();
        insert project;

        Boolean isExcetion;
        try {
            BISBackLinkGenerator.generateLinkForProject(project.Id);
        } catch (BISBackLinkGenerator.BISBackLinkGeneratorException e) {
            isExcetion = true;
        }
        System.assert(isExcetion);
    }
}