force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-641</description>
    <label>Projekt Team - Mitglied</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Team - Mitglieder</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Not integration relevant
2. ZR
3. SF-1211</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/Project_Territory__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE sends Territories)
2. CORE / ZR
3.</description>
    <label>Projekt Vertriebsgebiet</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Project Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Vertriebsgebiete</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Territory__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Specifies which Business Area the Territory belongs to</description>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potential</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Project_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Stores the Territory ID from GRACE (e.g. M101)</description>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Filled by Flow</description>
    <label>Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory2/fields/Core_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Core_External_ID__c</fullName>
    <description>1. Integration relevant (Grace)
2. CORE
3.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Potential.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>EEB (EKW)</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>LC</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Rent</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>TS</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <isActive>false</isActive>
        <label>SuK</label>
    </customValue>
    <masterLabel>Potential</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>19</fullName>
        <label>Account Manager Recommendation</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Campaign</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Call</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Construction Information Systems</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Construction Site Visits</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Customer Call</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Customer Recommendation</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Customer Visit/ Customer information</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Email Mailing</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Lead Purchase</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Postal Mailing</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Public announcement - Building lot</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>Public announcement - Trade lot</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Request</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Trade Show</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Webpages / Portals</label>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlowActionProjectTeamMemberTest.cls
/**
 * Test class for "FlowActionProjectTeamMember".
 * 
 * @author	miriam.ida.tyroller@accenture.com
 *
 * @version 2023-08-23	miriam.ida.tyroller@accenture.com		creation
 */
@IsTest(SeeAllData=false)
public without sharing class FlowActionProjectTeamMemberTest {

    /**
     * Creates test project, the creation needs to be placed seperately in an TestSetup method to avoid mixed dml operations
     */
    @TestSetup
    public static void createProjects(){
        Project__c proj1 = new Project__c();
        proj1.Name = 'Test Project 1';
        proj1.Project_Address__CountryCode__s = 'DE';
        proj1.Project_Address__City__s = 'TestCity';
        proj1.Project_Address__PostalCode__s = '12345';
        proj1.Project_Address__Street__s = 'Test Street';
        proj1.Core_Source_System__c = 'BIS';
        proj1.Project_Source__c = '29';
        proj1.Project_Construction_Progress__c = '7';
        proj1.Exact_Source__c = 'iBau';
        proj1.Active__c = true;
        insert proj1;

        Project__c proj2 = new Project__c();
        proj2.Name = 'Test Project 2';
        proj2.Project_Address__CountryCode__s = 'DE';
        proj2.Project_Address__City__s = 'TestCity';
        proj2.Project_Address__PostalCode__s = '12345';
        proj2.Project_Address__Street__s = 'Test Street';
        proj2.Core_Source_System__c = 'BIS';
        proj2.Project_Source__c = '29';
        proj2.Project_Construction_Progress__c = '7';
        proj2.Exact_Source__c = 'iBau';
        proj2.Active__c = true;
        insert proj2;
    }

    public static void createTestData(){
        Profile prof = [SELECT Id FROM Profile WHERE Name LIKE '%Administrator%' LIMIT 1]; 
        User us1 = new User(Alias = 'ATU1',Email = 'ApexTestUser@test.test',EmailEncodingKey = 'UTF-8',LastName = 'Apex Test User 1',LanguageLocaleKey = 'en_US',LocaleSidKey = 'de_DE_EURO',ProfileId = prof.Id,TimeZoneSidKey = 'Europe/Berlin',UserName = 'ApexTestUser1@test.test');
        insert us1;

        User us2 = new User(Alias = 'ATU2',Email = 'ApexTestUser@test.test',EmailEncodingKey = 'UTF-8',LastName = 'Apex Test User 2',LanguageLocaleKey = 'en_US',LocaleSidKey = 'de_DE_EURO',ProfileId = prof.Id,TimeZoneSidKey = 'Europe/Berlin',UserName = 'ApexTestUser2@test.test');
        insert us2;

        User us3 = new User(Alias = 'ATU3',Email = 'ApexTestUser@test.test',EmailEncodingKey = 'UTF-8',LastName = 'Apex Test User 3',LanguageLocaleKey = 'en_US',LocaleSidKey = 'de_DE_EURO',ProfileId = prof.Id,TimeZoneSidKey = 'Europe/Berlin',UserName = 'ApexTestUser3@test.test');
        insert us3;

        // Query one existing Territory to reuse the needed attributes
        Territory2 randomExistingTtr = [SELECT Id, Territory2TypeId, Territory2ModelId FROM Territory2 LIMIT 1];

        UserTerritory2Association usTerrAssoc1 = new UserTerritory2Association();
        usTerrAssoc1.UserId = us1.Id;
        usTerrAssoc1.Territory2Id = randomExistingTtr.Id;
        usTerrAssoc1.RoleInTerritory2 = 'Assistant';
        insert usTerrAssoc1;

        UserTerritory2Association usTerrAssoc2 = new UserTerritory2Association();
        usTerrAssoc2.UserId = us2.Id;
        usTerrAssoc2.Territory2Id = randomExistingTtr.Id;
        usTerrAssoc2.RoleInTerritory2 = 'Assistant';
        insert usTerrAssoc2;

        UserTerritory2Association usTerrAssoc3 = new UserTerritory2Association();
        usTerrAssoc3.UserId = us3.Id;
        usTerrAssoc3.Territory2Id = randomExistingTtr.Id;
        usTerrAssoc3.RoleInTerritory2 = 'Assistant';
        insert usTerrAssoc3;
    }



    @IsTest
    static void test_insertProjectTerrExistingTeamMember() {
        createTestData();
        User us1 =[SELECT Id FROM User WHERE Username = 'ApexTestUser1@test.test' LIMIT 1];
        User us2 =[SELECT Id FROM User WHERE Username = 'ApexTestUser2@test.test' LIMIT 1];
        User us3 =[SELECT Id FROM User WHERE Username = 'ApexTestUser3@test.test' LIMIT 1];
        UserTerritory2Association usTerrAssoc = [SELECT Id, Territory2Id FROM UserTerritory2Association WHERE UserId = : us1.Id LIMIT 1];
        Territory2 randomExistingTtr = [SELECT Id, DeveloperName, Core_External_ID__c FROM Territory2 WHERE Id = : usTerrAssoc.Territory2Id LIMIT 1];
        Project__c proj1 = [SELECT Id FROM Project__c WHERE Name = 'Test Project 1'];

        Project_Territory__c projTerr = new Project_Territory__c();
        projTerr.Project__c = proj1.Id;
        projTerr.Territory_ID__c = randomExistingTtr.Core_External_ID__c;
        projTerr.Territory_Name__c = randomExistingTtr.DeveloperName;
        projTerr.Business_Area__c = '1';

        List<Project_Team__c> newTeamMembers = new List<Project_Team__c>();

        Project_Team__c projTeamMember1 = new Project_Team__c();
        projTeamMember1.Project__c = proj1.Id;
        projTeamMember1.Team_Member__c = us1.Id;
        newTeamMembers.add(projTeamMember1);

        Project_Team__c projTeamMember2 = new Project_Team__c();
        projTeamMember2.Project__c = proj1.Id;
        projTeamMember2.Team_Member__c = us3.Id;
        newTeamMembers.add(projTeamMember2);

        List<UserTerritory2Association> usTerrAssocs = [SELECT Id, UserId, RoleInTerritory2 FROM UserTerritory2Association WHERE Territory2Id = : randomExistingTtr.Id];

        List<FlowActionProjectTeamMember.InputVariables> inputVariables = new List<FlowActionProjectTeamMember.InputVariables>();
        FlowActionProjectTeamMember.InputVariables inputVar = new FlowActionProjectTeamMember.InputVariables();
        inputVar.project = proj1.Id;
        inputVar.userTerritoryAssociations = usTerrAssocs;
        inputVariables.add(inputVar);

        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            Test.startTest();
                insert newTeamMembers;
                insert projTerr;
                FlowActionProjectTeamMember.createProjectTeamMembers(inputVariables);
            Test.stopTest();
        }
        
        assertProjectTeamMembers(proj1.Id, us1.Id, 1);
        assertProjectTeamMembers(proj1.Id, us2.Id, 1);
        assertProjectTeamMembers(proj1.Id, us3.Id, 1);
    }

    @IsTest
    static void test_insertProjectTerrNoTeamMember() {
        createTestData();
        User us1 =[SELECT Id FROM User WHERE Username = 'ApexTestUser1@test.test' LIMIT 1];
        User us2 =[SELECT Id FROM User WHERE Username = 'ApexTestUser2@test.test' LIMIT 1];
        User us3 =[SELECT Id FROM User WHERE Username = 'ApexTestUser3@test.test' LIMIT 1];
        UserTerritory2Association usTerrAssoc = [SELECT Id, Territory2Id FROM UserTerritory2Association WHERE UserId = : us1.Id LIMIT 1];
        Territory2 randomExistingTtr = [SELECT Id, DeveloperName, Core_External_ID__c FROM Territory2 WHERE Id = : usTerrAssoc.Territory2Id LIMIT 1];
        Project__c proj2 = [SELECT Id FROM Project__c WHERE Name = 'Test Project 2'];

        Project_Territory__c projTerr = new Project_Territory__c();
        projTerr.Project__c = proj2.Id;
        projTerr.Territory_ID__c = randomExistingTtr.Core_External_ID__c;
        projTerr.Territory_Name__c = randomExistingTtr.DeveloperName;
        projTerr.Business_Area__c = '1';

        List<UserTerritory2Association> usTerrAssocs = [SELECT Id, UserId, RoleInTerritory2 FROM UserTerritory2Association WHERE Territory2Id = : randomExistingTtr.Id];

        List<FlowActionProjectTeamMember.InputVariables> inputVariables = new List<FlowActionProjectTeamMember.InputVariables>();
        FlowActionProjectTeamMember.InputVariables inputVar = new FlowActionProjectTeamMember.InputVariables();
        inputVar.project = proj2.Id;
        inputVar.userTerritoryAssociations = usTerrAssocs;
        inputVariables.add(inputVar);

        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            Test.startTest();
                insert projTerr;
                FlowActionProjectTeamMember.createProjectTeamMembers(inputVariables);
            Test.stopTest();
        }
        
        assertProjectTeamMembers(proj2.Id, us1.Id, 1);
        assertProjectTeamMembers(proj2.Id, us2.Id, 1);
        assertProjectTeamMembers(proj2.Id, us3.Id, 1);
    }

    /**
     *
     * Query projectTeamMembers and assert expected count
     *
     * @param projectId 
     * @param userId
     * @param count
     */
    private static void assertProjectTeamMembers(Id projectId, Id userId, Integer count) {
        List<Project_Team__c> projectTeamMembers = [
            SELECT Id, Project__c, Team_Member__c
            FROM Project_Team__c
            WHERE Project__c = : projectId AND Team_Member__c = : userId
        ];
        System.assertEquals(count, projectTeamMembers.size());
    }
}