force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Territory__c/Project_Territory__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE sends Territories)
2. CORE / ZR
3.</description>
    <label>Projekt Vertriebsgebiet</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Project Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Vertriebsgebiete</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Territory__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Project_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Stores the Territory ID from GRACE (e.g. M101)</description>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory2/fields/Core_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Core_External_ID__c</fullName>
    <description>1. Integration relevant (Grace)
2. CORE
3.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LWCHandlerUserDisplayComp.cls
/**
 * SF-1239 Projekt - Benutzer in zugew. Vertriebsgebieten
 * Handler class for LWC userDisplayComp that queries the users the lwc should display
 *
 * @author miriam.ida.tyroller@accenture.com
 *
 * @version 2023-10-13  miriam.ida.tyroller@accenture.com       creation
 */

public with sharing class LWCHandlerUserDisplayComp {

    /**
     * Queries all users views for a SobjectType a user has access to
     * 
     * @param currentObject object API name where lwc is place to find out for which Sobjecttype the users should be queried for
     * @param recordId object record ID of the record the lwc is placed on
     * 
     * @return list of users queried 
     */
    @AuraEnabled(cacheable=true)
    public static List<DataTableWrapper> queryUserData(String currentObject, String recordId){
        List<DataTableWrapper> response = new List<DataTableWrapper>();

        if(currentObject == '"Project__c"'){
            List<UserTerritory2Association> usTerrList = getUsersInProjectTerritory(recordId);

            if(usTerrList.size() > 0){
                for(UserTerritory2Association usTerrAssoc : usTerrList){
                    DataTableWrapper obj = new DataTableWrapper();
                    obj.userId = usTerrAssoc.Id;
                    obj.name = usTerrAssoc.User.Name;
                    obj.nameUrl = '/'+ usTerrAssoc.User.Id;
                    obj.email = usTerrAssoc.User.Email;
                    obj.role = usTerrAssoc.RoleInTerritory2;
                    obj.territory = usTerrAssoc.Territory2.Name;
                    response.add(obj);
                }
            }
        }

        return response;
    }

    /**
     * Queries all users for a project in its assigned project territories
     * 
     * @param recordId Id of the project
     * 
     * @return list of users in project territories 
     */
    @AuraEnabled(cacheable=true)
    public static List<UserTerritory2Association> getUsersInProjectTerritory(String recordId){
        List<UserTerritory2Association> usTerrList = new List<UserTerritory2Association>();
        
        List<Project_Territory__c> projTerrList = [SELECT Id, Project__c, Territory_ID__c FROM Project_Territory__c WHERE Project__c = : recordId];

        if(projTerrList.size() > 0){
            Set<String> terrIds = new Set<String>();

            for (Project_Territory__c projTerr : projTerrList){
                terrIds.add(projTerr.Territory_ID__c);
            }

            Map<Id,Territory2> territoriesById = new Map<Id,Territory2>([SELECT Id FROM Territory2 WHERE Core_External_ID__c IN : terrIds]);

            if(territoriesById.values().size() > 0){
                usTerrList = [SELECT Id, User.Id, User.Name, User.Email, Territory2.Name, toLabel(RoleInTerritory2) FROM UserTerritory2Association WHERE Territory2Id IN : territoriesById.keySet()];
            }
        }

        return usTerrList;
    }

    public class DataTableWrapper {
        @AuraEnabled
        public Id userId {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String nameUrl {get;set;}
        @AuraEnabled
        public String email {get;set;}
        @AuraEnabled
        public String role {get;set;}
        @AuraEnabled
        public String territory {get;set;}
    }
}