force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Helper Field to be able to search through the Address Fields. Filled by Flow &quot;ZR_Project_Before_Insert_Flow&quot; and &quot;ZR_Project_Before_Update_Flow&quot;</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/Project_Territory__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE sends Territories)
2. CORE / ZR
3.</description>
    <label>Projekt Vertriebsgebiet</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Project Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Vertriebsgebiete</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Territory__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Project_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Stores the Territory ID from GRACE (e.g. M101)</description>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TTRCreateProjectTerritoriesBatchTest.cls
/**
 * SF-1058
 * Test class for TTRCreateProjectTerritoriesBatch.
 *
 * @group TTR Territories
 * @date 2023-05-05
 * @author rene.pienkoss@accenture.com
 */
@IsTest
public with sharing class TTRCreateProjectTerritoriesBatchTest {
    
    public static final String postalCode = '07743';

    /**
     * Test Setup
     */
    @TestSetup
	private static void createTestData() {
        // Project
        Project__c project = new Project__c();
        project.Name = 'Test Project';

        project.Project_Address__CountryCode__s = 'DE';
        project.Project_Address__City__s = 'TestCity';
        project.Project_Address__PostalCode__s = postalCode;
        project.Project_Address__Street__s = 'Test Street';
        //project.Postal_Code__c = postalCode;

        insert project;
    }

    /**
     * Test positive creation of Project_Territory__c.
     */
    @isTest 
    private static void testTerritoryCreationSuccess() {
        Test.startTest();

        TTRCreateProjectTerritoriesBatch myBatch = new TTRCreateProjectTerritoriesBatch();
        Database.executeBatch(myBatch, TTRCreateProjectTerritoriesBatch.defaultBatchSize);

        Test.stopTest();

        // validate results
        // query Projects and related Territories
        List<Project__c> projList = [SELECT Id, Postal_Code__c, 
                                            (SELECT Id, Project__c, Territory_ID__c 
                                                FROM Project_Territories__r)
                                        FROM Project__c];

        Assert.areEqual(1, projList.size(), 'Unexpected amount of Products');
        Assert.areEqual(4, projList[0].Project_Territories__r.size(), 'Unexpected amount of Project Territories');
    }
}