force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Start__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>Total_Volume__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/Project_Territory__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE sends Territories)
2. CORE / ZR
3.</description>
    <label>Projekt Vertriebsgebiet</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Project Territory Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Vertriebsgebiete</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Territory__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Specifies which Business Area the Territory belongs to</description>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potential</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Project_Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_ID__c.field-meta.xml
<CustomField>
    <fullName>Territory_ID__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZR
3. Stores the Territory ID from GRACE (e.g. M101)</description>
    <label>Territory ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Territory__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Filled by Flow</description>
    <label>Territory Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory2/fields/Core_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Core_External_ID__c</fullName>
    <description>1. Integration relevant (Grace)
2. CORE
3.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Potential.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>EEB (EKW)</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>LC</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Rent</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>TS</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <isActive>false</isActive>
        <label>SuK</label>
    </customValue>
    <masterLabel>Potential</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>19</fullName>
        <label>Account Manager Recommendation</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Campaign</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Call</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Construction Information Systems</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Construction Site Visits</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Customer Call</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Customer Recommendation</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Customer Visit/ Customer information</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Email Mailing</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Lead Purchase</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Postal Mailing</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Public announcement - Building lot</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>Public announcement - Trade lot</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Request</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Trade Show</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Webpages / Portals</label>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LWCHandlerUserDisplayCompTest.cls
/**
 * SF-1239:  test class for LWCHandlerUserDisplayComp
 * 
 * @author  miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-10-12  miriam.ida.tyroller       creation
 */

@IsTest
public with sharing class LWCHandlerUserDisplayCompTest {
    
    @TestSetup
    public static void createTestData(){

        // Query one existing Territory to reuse the needed attributes
        List<Territory2> randomExistingTTrs = [SELECT Id, Territory2TypeId, Territory2ModelId FROM Territory2 LIMIT 3];
        Id ttrTypeId = randomExistingTTrs[2].Territory2TypeId;
        Id ttrModelId = randomExistingTTrs[2].Territory2ModelId;
        Id ttrParentId = randomExistingTTrs[2].Id;

        Territory2 terr1 = new Territory2(
            AccountAccessLevel = 'Edit',
            CaseAccessLevel = 'None',
            DeveloperName = 'ZR_Mietstation_5',
            Name = 'ApexTestTerritory 5',
            Core_External_ID__c = 'M999',
            OpportunityAccessLevel = 'Edit',
            Territory2ModelId = ttrModelId,
            Territory2TypeId = ttrTypeId,
            ParentTerritory2Id = ttrParentId
        );
        insert terr1;

        Profile prof = [SELECT Id FROM Profile WHERE Name LIKE '%Administrator%' LIMIT 1]; 
        User us1 = new User(Alias = 'ATU5',
                            Email = 'ApexTestUser5@test.test',
                            EmailEncodingKey = 'UTF-8',
                            LastName = 'Apex Test User 5',
                            LanguageLocaleKey = 'en_US',
                            LocaleSidKey = 'de_DE_EURO',
                            ProfileId = prof.Id,
                            TimeZoneSidKey = 'Europe/Berlin',
                            UserName = 'ApexTestUser5@test.test');
        insert us1;

        UserTerritory2Association usTerrAssoc1 = new UserTerritory2Association();
        usTerrAssoc1.UserId = us1.Id;
        usTerrAssoc1.Territory2Id = terr1.Id;
        usTerrAssoc1.RoleInTerritory2 = 'Assistant';
        insert usTerrAssoc1;

        

    }

    @IsTest
    public static void test_queryUserData() {
        Date todayDate = Date.today();

        // ibau project 
        Project__c project1 = new Project__c();
        project1.Name = 'Test Project 1';
        project1.Project_Address__CountryCode__s = 'DE';
        project1.Project_Address__City__s = 'TestCity';
        project1.Project_Address__PostalCode__s = '12345';
        project1.Project_Address__Street__s = 'Test Street';
        project1.Core_Source_System__c = 'BIS';
        project1.Project_Source__c = '29';
        project1.Project_Construction_Progress__c = '7';
        project1.Exact_Source__c = 'iBau';
        project1.Project_Construction_Start__c = todayDate;
        project1.Total_Volume__c = 2000.00;
        project1.Active__c = true;
        insert project1;

        Project_Territory__c projTerr = new Project_Territory__c();
        projTerr.Project__c = project1.Id;
        projTerr.Territory_ID__c = 'M999';
        projTerr.Territory_Name__c = 'ZR_Mietstation_5';
        projTerr.Business_Area__c = '1';
        insert projTerr; 

        Test.startTest();
            List<LWCHandlerUserDisplayComp.DataTableWrapper> userList = LWCHandlerUserDisplayComp.queryUserData('"Project__c"', project1.Id);
        Test.stopTest();

        System.assertEquals(1,userList.size());
    }

}