force-app/main/default/objects/BIS_Project_Import_Config__c/BIS_Project_Import_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BIS Project Import Config</label>
</CustomObject>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Ibau_Month_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Ibau_Month_Limit__c</fullName>
    <label>Deletion Ibau Month Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Infobau_Month_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Infobau_Month_Limit__c</fullName>
    <label>Deletion Infobau Month Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant 
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration irrelevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF- 725</description>
    <label>Auftrag.</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aufträge.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Not integration relevant
2. ZR
3.</description>
    <inlineHelpText>Only Opportunities that are linked to the Account of this Order, have the same Business Area as this Order and are in the Quotation- or Closed-Won-Stage can be connected.</inlineHelpText>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>notEqual</operation>
            <value>Neu, Qualifizierungsphase, Geschlossen - Verloren</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.Business_Area__c</field>
            <operation>equals</operation>
            <valueField>$Source.Business_Area__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Quote_SF_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_SF_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant
2. ZR
3.</description>
    <label>Quote SF ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_End__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_End__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Sales_Excellence_is_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Excellence_is_Owner__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-587 Helper Field to display &quot;Assign new Owner&quot; Quick Action only if the Sales Excellence Queue is the Owner of the project</description>
    <formula>Owner:Queue.QueueName = &quot;Sales Excellence&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Excellence is Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Contact_Relation__c/Project_Contact_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF- 61</description>
    <label>Projekt Kontakt Beziehung</label>
    <nameField>
        <displayFormat>PCR-{0000}</displayFormat>
        <label>Project Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Kontakt Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Contact_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Project_Contact_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-717</description>
    <label>Angebot.</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quote SF ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Angebote.</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. ZRD
3. SF-763</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Quotes_Rental</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BISProjectDeletionBatch.cls
/**
 * SF-1014:  job to delete Project__c records from BIS (ESB).
 * 
 * @author  miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-07-31  miriam.ida.tyroller       creation
 */

public with sharing class BISProjectDeletionBatch implements Database.Batchable<sObject>, Database.Stateful {

    public static final String CLASSNAME = 'BISProjectDeletionBatch';
    public String query;
    public static Integer defaultBatchSize = 350;

    // statistical values
    private Statistics stats;

    // the list of errors handled during execution 
    private List<Core_Error_Log__c> errorLogs;

    public BISProjectDeletionBatch() {
        this.stats = new Statistics();
        this.errorLogs = new List<Core_Error_Log__c>();
    }

    /**
     * The start method is called at the beginning of the batch Apex job.
     * 
     * This method returns the Database.QueryLocator that contains the projetcs records where the source system 
     * is BIS and the construction end is already exceeded, which will then be checked if they should be deleted. 
     * 
     * @param bc    Database.BatchableContext
     * 
     * @return Database.QueryLocator for Project__c records
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('########## RP BISProjectDeletionBatch: start');

        Date todayDate = Date.today();

        if (this.query == null) {
            this.query = 'SELECT Id FROM Project__c WHERE Core_Source_System__c = \'BIS\' AND Project_Construction_End__c <= : todayDate';
        }

        return Database.getQueryLocator(this.query);
    }

    /**
     * The execute method is called for each batch of projects records passed to the method and decides
     * by a logic which BIS projects should be deleted and which updated to status !active
     * 
     * @param bc    Database.BatchableContext
     * @param scope List of Project__c records to be processed
     */
    public void execute(Database.BatchableContext bc, List<Project__c> scope) {
        Integer infobauMonthLimit = (Integer) BIS_Project_Import_Config__c.getOrgDefaults().Deletion_Infobau_Month_Limit__c;
        Integer ibauMonthLimit = (Integer) BIS_Project_Import_Config__c.getOrgDefaults().Deletion_Ibau_Month_Limit__c;

        Date infoBauLimit = Date.today().addMonths(-infobauMonthLimit);
        Date iBauLimit = Date.today().addMonths(-ibauMonthLimit);

        System.debug('########## RP BISProjectDeletionBatch: execute: ' + scope.size());

        try {
            List<Project__c> projectsToDelete = new List<Project__c>();
            List<Project__c> projectsToUpdate = new List<Project__c>();
            
            // query projects and related accounts, contacts, opportunities, quotes, orders, tasks and events
            List<Project__c> projList = [
                SELECT 
                Id, 
                Project_Construction_Progress__c,
                Sales_Excellence_is_Owner__c,
                Exact_Source__c, 
                Project_Construction_End__c, 
                (SELECT Id, Project__c 
                        FROM Project_Account_Relations__r LIMIT 1), 
                (SELECT Id, Project__c 
                        FROM Project_Contact_Relations__r LIMIT 1), 
                (SELECT Id, Project__c 
                        FROM Opportunities__r LIMIT 1),
                (SELECT Id, Project__c 
                        FROM Quotes_Rental__r LIMIT 1),
                (SELECT Id, Project__c 
                        FROM Orders__r LIMIT 1), 
                (SELECT Id, WhatId 
                        FROM Tasks LIMIT 1), 
                (SELECT Id, WhatId 
                        FROM Events LIMIT 1)
                FROM Project__c 
                WHERE Id IN :scope];

            this.stats.projectCount += projList.size();

            for (Project__c proj : projList) {
                //only deactivate / delete ibau projects with the progress 7 -> Shortly before Completion / Completion 
                if(proj.Exact_Source__c == 'iBau' && proj.Project_Construction_Progress__c == '7'){
                    //only delete projects with no related accounts, contacts, opportunities, quotes, orders, tasks and events
                    if(
                            proj.Project_Account_Relations__r.size() == 0 &&
                            proj.Project_Contact_Relations__r.size() == 0 &&
                            proj.Opportunities__r.size() == 0 &&
                            proj.Quotes_Rental__r.size() == 0 &&
                            proj.Orders__r.size() == 0 &&
                            proj.Tasks.size() == 0 &&
                            proj.Events.size() == 0 ){
                                //only delete projects where the construction end is twelve months or longer ago
                                if(proj.Project_Construction_End__c <= iBauLimit ){
                                    projectsToDelete.add(proj);
                                }
                                else{
                                    //deactivate projects without related records after the construction end has passed
                                    proj.Active__c = false;
                                    projectsToUpdate.add(proj);
                                }
                                
                    }
                    else{
                        //only deactivate projects with related records after the construction end has passed 
                        //if the owner is not Sales Excellence
                        if(!proj.Sales_Excellence_is_Owner__c){
                            proj.Active__c = false;
                            projectsToUpdate.add(proj);
                        }
                    }
                }
                else if(proj.Exact_Source__c == 'infoBau'){
                    //only delete projects with no related accounts, contacts, opportunities, quotes, orders, tasks and events
                    if(
                        proj.Project_Account_Relations__r.size() == 0 &&
                        proj.Project_Contact_Relations__r.size() == 0 &&
                        proj.Opportunities__r.size() == 0 &&
                        proj.Quotes_Rental__r.size() == 0 &&
                        proj.Orders__r.size() == 0 &&
                        proj.Tasks.size() == 0 &&
                        proj.Events.size() == 0 ){
                            //only delete projects where the construction end is six months or longer ago
                            if(proj.Project_Construction_End__c <= infoBauLimit){
                                projectsToDelete.add(proj);
                            }
                            else{
                                //deactivate projects without related records after the construction end has passed
                                proj.Active__c = false;
                                projectsToUpdate.add(proj);
                            }
                    }
                    else{
                        //deactivate projects with no related records after the construction end has passed
                        proj.Active__c = false;
                        projectsToUpdate.add(proj);
                    }
                }       
            }


            System.debug(projectsToDelete.size() + ' projects will be deleted.');
            this.stats.projectsDeletedCount += projectsToDelete.size();

            //delete all projects fitting the above criteria
            if(!projectsToDelete.isEmpty()) {
                Database.DeleteResult[] projectDeleteResult = Database.delete(projectsToDelete, false);
                // check results and create error logs
                Integer i = 0;
                for (Database.DeleteResult dr : projectDeleteResult) {
                    if (!dr.isSuccess()) {
                        Id projId = projectsToDelete[i].Id;

                        String errorMessage = 'Error while deleting Project__c record with ID ' + projId;
                        String exceptionMessage = dr.getErrors()[0].getStatusCode() + ': ' + dr.getErrors()[0].getMessage();

                        System.debug('########## RP exceptionMessage: ' + exceptionMessage);
                        this.errorLogs.add(UTLErrorLog.createErrorLogRecord(CLASSNAME, new HandledException(exceptionMessage), errorMessage, projId));
                    }
                    i++;
                }
            }

            System.debug(projectsToUpdate.size() + ' projects will be updated.');
            this.stats.projectsUpdatedCount += projectsToUpdate.size();

            //deactivate all projects fitting the above criteria
            if(!projectsToUpdate.isEmpty()) {
                Database.SaveResult[] projectUpdateResult = Database.update(projectsToUpdate, false);
                // check results and create rerror logs
                Integer i = 0;
                for (Database.SaveResult sr : projectUpdateResult) {
                    if (!sr.isSuccess()) {
                        Id projId = projectsToUpdate[i].Id;

                        String errorMessage = 'Error while updating Project__c record with ID ' + projId;
                        String exceptionMessage = sr.getErrors()[0].getStatusCode() + ': ' + sr.getErrors()[0].getMessage();

                        System.debug('########## RP exceptionMessage: ' + exceptionMessage);
                        this.errorLogs.add(UTLErrorLog.createErrorLogRecord(CLASSNAME, new HandledException(exceptionMessage), errorMessage, projId));
                    }
                    i++;
                }
            }
        }
        catch (Exception e) {
            System.debug('########## RP Exception: ' + e.getMessage() + '. Line: ' + e.getLineNumber() + '. TraceString: ' + e.getStackTraceString() );
            this.errorLogs.add(UTLErrorLog.createErrorLogRecord(CLASSNAME, e, e.getMessage(), null));
        }
        
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('########## RP BISProjectDeletionBatch: finish');

        System.debug('########## RP stats: ' + this.stats);
        System.debug('########## RP projectCount: ' + this.stats.projectCount);
        System.debug('########## RP projectsDeletedCount: ' + this.stats.projectsDeletedCount);
        System.debug('########## RP projectsUpdatedCount: ' + this.stats.projectsUpdatedCount);

        UTLErrorLog.insertErrorLogs(this.errorLogs, CLASSNAME);
    }

    /**
     * Wrapper class to collect statistical values
     */
    private class Statistics {
        private Integer projectCount;
        private Integer projectsDeletedCount;
        private Integer projectsUpdatedCount;

        /**
         * Constructor
         */
        public Statistics() {
            this.projectCount = 0;
            this.projectsDeletedCount = 0;
            this.projectsUpdatedCount = 0;
        }

    }
}