force-app/main/default/objects/BIS_Project_Import_Config__c/BIS_Project_Import_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BIS Project Import Config</label>
</CustomObject>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Batch_Size__c</fullName>
    <label>Deletion Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BISProjectDeletionBatchScheduler.cls
/**
 * SF-1014: Scheduler for infobau / ibau project deletion job (BISProjectDeletion)
 * 
 * @author  miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-07-31  miriam.ida.tyroller@accenture.com     creation
 */
public class BISProjectDeletionBatchScheduler implements Schedulable {

    private static Integer BATCH_SIZE = (Integer) BIS_Project_Import_Config__c.getOrgDefaults().Deletion_Batch_Size__c;
    
    /**
     * The execute method is used to instantiate the class to be scheduled.
     */
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new BISProjectDeletionBatch(), BATCH_SIZE);
    }
}