force-app/main/default/objects/Account/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-763</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Save_without_Email__c.field-meta.xml
<CustomField>
    <fullName>Save_without_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1. Not integration relevant
2. ZR
3. Use this field to disable the validation rule that is set on the Email address field to save an account without an email address</description>
    <inlineHelpText>If you want to save an Account without an Email address please check this checkbox.</inlineHelpText>
    <label>Save without Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/BIS_Project_Import_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BIS Project Import Config</label>
</CustomObject>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Batch_Size__c</fullName>
    <label>Deletion Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Ibau_Month_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Ibau_Month_Limit__c</fullName>
    <label>Deletion Ibau Month Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Deletion_Infobau_Month_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deletion_Infobau_Month_Limit__c</fullName>
    <label>Deletion Infobau Month Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Not integration relevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Save_without_Email__c.field-meta.xml
<CustomField>
    <fullName>Save_without_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZR
3. Use this field to disable the validation rule that is set on the Email address field to save a contact without an email address</description>
    <inlineHelpText>If you want to save a Contact without an Email address please check this box.</inlineHelpText>
    <label>Save without Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant 
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration irrelevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF- 725</description>
    <label>Auftrag.</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aufträge.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_End__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_End__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Contact_Relation__c/Project_Contact_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF- 61</description>
    <label>Projekt Kontakt Beziehung</label>
    <nameField>
        <displayFormat>PCR-{0000}</displayFormat>
        <label>Project Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Kontakt Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Contact_Relation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Deletion_Code__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Contact_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Contact_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Project_Contact_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>19</fullName>
        <label>Account Manager Recommendation</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Campaign</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Call</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Construction Information Systems</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Construction Site Visits</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Customer Call</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Customer Recommendation</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Customer Visit/ Customer information</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Email Mailing</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Lead Purchase</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Postal Mailing</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Public announcement - Building lot</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>Public announcement - Trade lot</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Request</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Trade Show</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Webpages / Portals</label>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BISProjectDeletionBatchTest.cls
/**
 * SF-1014:  test class for BISProjectDeletionBatch
 * 
 * @author  miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-07-31  miriam.ida.tyroller       creation
 */
@IsTest
public with sharing class BISProjectDeletionBatchTest {
    
    @TestSetup
    public static void createTestData(){
        BIS_Project_Import_Config__c bisConf = new BIS_Project_Import_Config__c(SetupOwnerId = UserInfo.getOrganizationId());
        bisConf.Deletion_Batch_Size__c = 350;
        bisConf.Deletion_Infobau_Month_Limit__c = 6;
        bisConf.Deletion_Ibau_Month_Limit__c = 12;
        insert bisConf;

        Date todayDate = Date.today();
        Date futureDate = Date.today().addMonths(1);
        Date sixMonthsLimit = Date.today().addMonths(-6);
        Date oneYearLimit = Date.today().addMonths(-12);

        Territory2 randomExistingTtr = [SELECT Id, Territory2TypeId, Territory2ModelId FROM Territory2 LIMIT 1];

        // ibau don't delete
        Project__c project1 = new Project__c();
        project1.Name = 'Test Project 1';
        project1.Project_Address__CountryCode__s = 'DE';
        project1.Project_Address__City__s = 'TestCity';
        project1.Project_Address__PostalCode__s = '12345';
        project1.Project_Address__Street__s = 'Test Street';
        project1.Core_Source_System__c = 'BIS';
        project1.Project_Source__c = '29';
        project1.Project_Construction_Progress__c = '7';
        project1.Exact_Source__c = 'iBau';
        project1.Project_Construction_End__c = oneYearLimit;
        project1.Active__c = true;
        insert project1;

        // infobau don't delete
        Project__c project2 = new Project__c();
        project2.Name = 'Test Project 2';
        project2.Project_Address__CountryCode__s = 'DE';
        project2.Project_Address__City__s = 'Test Town';
        project2.Project_Address__PostalCode__s = '99999';
        project2.Project_Address__Street__s = 'Test Street';
        project2.Core_Source_System__c = 'BIS';
        project2.Project_Source__c = '29';
        project2.Project_Construction_Progress__c = '7';
        project2.Exact_Source__c = 'infoBau';
        project2.Project_Construction_End__c = oneYearLimit;
        project2.Active__c = true;
        insert project2;

        // ibau Project delete
        Project__c project3 = new Project__c();
        project3.Name = 'Test Project 3';
        project3.Project_Address__CountryCode__s = 'DE';
        project3.Project_Address__City__s = 'TestCity';
        project3.Project_Address__PostalCode__s = '88888';
        project3.Project_Address__Street__s = 'Test Street';
        project3.Core_Source_System__c = 'BIS';
        project3.Project_Source__c = '29';
        project3.Project_Construction_Progress__c = '7';
        project3.Exact_Source__c = 'iBau';
        project3.Project_Construction_End__c = oneYearLimit;
        project3.Active__c = true;
        insert project3;

        // infobau Project delete
        Project__c project4 = new Project__c();
        project4.Name = 'Test Project 4';
        project4.Project_Address__CountryCode__s = 'DE';
        project4.Project_Address__City__s = 'Test Town';
        project4.Project_Address__PostalCode__s = '77777';
        project4.Project_Address__Street__s = 'Test Street';
        project4.Core_Source_System__c = 'BIS';
        project4.Project_Source__c = '29';
        project4.Project_Construction_Progress__c = '7';
        project4.Exact_Source__c = 'infoBau';
        project4.Project_Construction_End__c = oneYearLimit;
        project4.Active__c = true;
        insert project4;

        //infobau Project don't delete
        Project__c project5 = new Project__c();
        project5.Name = 'Test Project 5';
        project5.Project_Address__CountryCode__s = 'DE';
        project5.Project_Address__City__s = 'Test Town';
        project5.Project_Address__PostalCode__s = '77777';
        project5.Project_Address__Street__s = 'Test Street';
        project5.Core_Source_System__c = 'BIS';
        project5.Project_Source__c = '29';
        project5.Project_Construction_Progress__c = '7';
        project5.Exact_Source__c = 'infoBau';
        project5.Project_Construction_End__c = todayDate;
        project5.Active__c = true;
        insert project5;

        //ibau Project don't delete
        Project__c project6 = new Project__c();
        project6.Name = 'Test Project 6';
        project6.Project_Address__CountryCode__s = 'DE';
        project6.Project_Address__City__s = 'Test Town';
        project6.Project_Address__PostalCode__s = '77777';
        project6.Project_Address__Street__s = 'Test Street';
        project6.Core_Source_System__c = 'BIS';
        project6.Project_Source__c = '29';
        project6.Project_Construction_Progress__c = '7';
        project6.Exact_Source__c = 'iBau';
        project6.Project_Construction_End__c = futureDate;
        project6.Active__c = true;
        insert project6;

        Account acc = new Account(Name = 'Test Acc');
        acc.Save_without_Email__c = true;
        acc.BillingCity = 'Test City';
        acc.BillingPostalCode = '12345';
        acc.BillingStreet = 'Test Street 1';
        insert acc;

        Contact con = new Contact();
        con.FirstName = 'Deletion';
        con.LastName = 'Test 1';
        con.AccountId = acc.Id;
        con.MobilePhone = '+49123456789';
        con.Salutation = 'Mr.';
        con.Email = 'testcon@accenture.com';
        insert con;

        Project_Account_Relation__c projAccRelation1 = new Project_Account_Relation__c();
        projAccRelation1.Account__c = acc.Id;
        projAccRelation1.Project__c = project1.Id;
        insert projAccRelation1;

        Project_Account_Relation__c projAccRelation2 = new Project_Account_Relation__c();
        projAccRelation2.Account__c = acc.Id;
        projAccRelation2.Project__c = project2.Id;
        insert projAccRelation2;

        Project_Contact_Relation__c projConRelation1 = new Project_Contact_Relation__c();
        projConRelation1.Contact__c = con.Id;
        projConRelation1.Project__c = project1.Id;
        insert projConRelation1;

        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test Opp';
        opp1.StageName = 'New';
        opp1.CloseDate = todayDate;
        opp1.Project__c = project1.Id;
        opp1.Construction_Site_Address__CountryCode__s = 'DE';
        opp1.Construction_Site_Address__City__s = 'TestCity';
        opp1.Construction_Site_Address__PostalCode__s = '55555';
        opp1.Construction_Site_Address__Street__s = 'Test Street';
        insert opp1;
      
        Order__c order1 = new Order__c();
        order1.Project__c = project1.Id;
        insert order1;

        Order__c order2 = new Order__c();
        order2.Project__c = project2.Id;
        insert order2;

        Task task1 = new Task();
        task1.WhatId = project1.Id;
        insert task1;
    }

    @IsTest
    public static void test_deleteIbauProjects() {
        assertIBauProjects(3);

        Test.startTest();
            Database.executeBatch(new BISProjectDeletionBatch(), 350);
        Test.stopTest();

        assertIBauProjects(2);
    }

    @IsTest
    public static void test_deleteInfobauProjects() {
        assertInfoBauProjects(3);

        Test.startTest();
            Database.executeBatch(new BISProjectDeletionBatch(), 350);
        Test.stopTest();

        assertInfoBauProjects(2);
    }

    @IsTest
    public static void test_deactivateProjects() {
        assertInactiveProjects(0);

        Test.startTest();
            Database.executeBatch(new BISProjectDeletionBatch(), 350);
        Test.stopTest();

        assertInactiveProjects(3);
    }

    @IsTest
    public static void BISProjectDeletionBatchScheduler() {
        Test.startTest();
        
		String CRON_EXP = '0 0 0 3 9 ? 2080';
		String jobId = System.schedule('testScheduledApex', CRON_EXP, new BISProjectDeletionBatchScheduler());
        List<CronTrigger> ctList = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        
        Test.stopTest();
        
        System.assert(!ctList.isEmpty());
    }

    public static void assertIBauProjects(Integer count){
        System.debug([SELECT Id, Exact_Source__c FROM Project__c]);
        List<Project__c> projectList = [SELECT Id FROM Project__c WHERE Exact_Source__c = 'iBau'];
        System.assertEquals(count,projectList.size());
    }

    public static void assertInfoBauProjects(Integer count){
        List<Project__c> projectList = [SELECT Id FROM Project__c WHERE Exact_Source__c = 'infoBau'];
        System.assertEquals(count,projectList.size());
    }

    public static void assertInactiveProjects(Integer count){
        List<Project__c> projectList = [SELECT Id FROM Project__c WHERE Core_Source_System__c = 'BIS' AND Active__c = false];
        System.assertEquals(count,projectList.size());
    }

}