force-app/main/default/objects/Account/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-763</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/ZR_Standard_Account_Customer.recordType-meta.xml
<RecordType>
    <fullName>ZR_Standard_Account_Customer</fullName>
    <active>true</active>
    <description>Record type for accounts with type customer</description>
    <label>Account Customer</label>
</RecordType>

force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Lead__c/recordTypes/Account_Lead_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Account_Lead_Record_Type</fullName>
    <active>true</active>
    <description>1. Not integration relevant 2. ZR 3. SF-1155</description>
    <label>Account Lead Record Type</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (XFAIR)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Potential__c.field-meta.xml
<CustomField>
    <fullName>Potential__c</fullName>
    <description>1. Integration relevant (XFAIR)
2. ZR
3.</description>
    <inlineHelpText>Please enter the business segment for which this lead has potential.</inlineHelpText>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potential</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Building_Owner__c.field-meta.xml
<CustomField>
    <fullName>Building_Owner__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Filled by Flow &quot;Create Project screen Flow&quot;</description>
    <label>Building Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Building_Owner_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Building_Owner_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned building owner names</description>
    <label>Building Owner (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Helper Field to be able to search through the Address Fields. Filled by Flow &quot;ZR_Project_Before_Insert_Flow&quot; and &quot;ZR_Project_Before_Update_Flow&quot;</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/House_Number_cleaned__c.field-meta.xml
<CustomField>
    <fullName>House_Number_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned House Number data</description>
    <label>House Number (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Involved_Accounts_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Involved_Accounts_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 helper field to store cleaned involved Accounts names</description>
    <label>Involved Accounts (cleaned)</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Helper Field to be able to search through the Address Fields. Filled by Flow &quot;ZR_Project_Before_Insert_Flow&quot; and &quot;ZR_Project_Before_Update_Flow&quot;</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Potential__c.field-meta.xml
<CustomField>
    <fullName>Potential__c</fullName>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Potential</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potential</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-742</description>
    <label>Project Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Start__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. Helper Field to be able to search through the Address Fields. Filled by Flow &quot;ZR_Project_Before_Insert_Flow&quot; and &quot;ZR_Project_Before_Update_Flow&quot;</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Street_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Street_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned Street data</description>
    <label>Street (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>Total_Volume__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Salesforce_Project.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Project</fullName>
    <active>true</active>
    <description>Used to create Projects directly in Salesforce.</description>
    <label>Salesforce Project</label>
</RecordType>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Lead__c.field-meta.xml
<CustomField>
    <fullName>Account_Lead__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <referenceTo>Account_Lead__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant
2. ZR
3. SF-1155</description>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZRD
3. SF-1155</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Leads</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Account_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Architect</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Bidder</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Building Contractor</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Building Owner</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Consultant</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Further Participants</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>General Constructor</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Operating Firm</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Operator</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Planer</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Planer and Engineers</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Project Controller</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Project Developer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Property Surveillance</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Tenant</label>
    </customValue>
    <masterLabel>Account Role</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Potential.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>AU</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>EEB (EKW)</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>LC</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Rent</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>TS</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <isActive>false</isActive>
        <label>SuK</label>
    </customValue>
    <masterLabel>Potential</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FlowActionDuplicateCheckTest.cls
/**
 * SF-1205: Test class for FlowActionDuplicateCheck
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-25      isabella.moos@accenture.com     creation
 */
@IsTest
private with sharing class FlowActionDuplicateCheckTest {
    private static final String ACCOUNT_RECORD_TYPE_NAME = 'ZR_Standard_Account_Customer';
    private static final String ACCOUNT_LEAD_RECORD_TYPE_NAME = 'Account_Lead_Record_Type';
    private static final String SALESFORCE_PROJECT_RECORD_TYPE_NAME = 'Salesforce_Project';

    /**
     * Creates test project, the creation needs to be placed seperately in an TestSetup method to avoid mixed dml operations
     */
    @TestSetup
    private static void createTestData() {
        //create accounts
        List<Account> testAccountList = TESTDataFactory.createTestAccounts(1, ACCOUNT_RECORD_TYPE_NAME, false);
        testAccountList.addAll(TESTDataFactory.createTestAccounts(1, ACCOUNT_RECORD_TYPE_NAME, false));
        testAccountList[1].Name = 'Test Acc 2';
        insert testAccountList;

        //create account leads
        List<Account_Lead__c> testAccountLeadList = TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false);
        testAccountLeadList.addAll(TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false));
        testAccountLeadList[1].Name = 'Test Acc 2';
        insert testAccountLeadList;

        //create projects
        List<Project__c> testProjectList = TESTDataFactory.createTestIBauProjects(2, SALESFORCE_PROJECT_RECORD_TYPE_NAME, true);

        //create project account relations
        List<Project_Account_Relation__c> testPPARList = TESTDataFactory.createTestPARs(1, testAccountList[1], '1', testProjectList[0], false);
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '2', testProjectList[0], false));
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '1;3', testProjectList[0], false));
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[1], '1', testProjectList[1], false));
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '2', testProjectList[1], false));
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '1;3', testProjectList[1], false));
        insert testPPARList;

        //create project account lead relations
        List<Project_Account_Lead_Relation__c> testPPALRList = TESTDataFactory.createTestPALRs(1, testAccountLeadList[1], '1', testProjectList[0], false);
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '3', testProjectList[0], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '2', testProjectList[0], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[1], '1', testProjectList[1], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '3', testProjectList[1], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '2', testProjectList[1], false));
        insert testPPALRList;
    }

    /**
     * Test InitDuplicateCheck method With Existing Project record (relevant for data creanse activities)
     */
    @isTest
    private static void testInitDuplicateCheckWithExistingProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();

        Map<Id,Project__c> projectMap = new Map<Id,Project__c>();
        List<Project__c> projectList = new List<Project__c> ();

        //query test record
        for(Project__c project : [SELECT 
                                    id, 
                                    Involved_Accounts_cleaned__c,
                                    Building_Owner_cleaned__c,
                                    Street_cleaned__c,
                                    House_Number_cleaned__c, 
                                    Project_Address__Street__s,
                                    (SELECT Id, Account__c, Account__r.Name, Project__c, Account_Role__c FROM Project_Account_Relations__r),
                                    (SELECT Id, Account_Lead__c, Account_Lead__r.Name, Project__c, Account_Role__c FROM Project_Account_Lead_Relations__r)  
                                FROM Project__c 
                                LIMIT 1]) {

            // reset helper fields
            project.Involved_Accounts_cleaned__c = null;
            project.Building_Owner_cleaned__c = null;
            project.Street_cleaned__c = null;
            project.House_Number_cleaned__c = null;
            List<Project_Account_Relation__c> projectAccountRelations = new List<Project_Account_Relation__c>();
            List<Account> relatedAccountsList = new List<Account>();
            List<Project_Account_Lead_Relation__c> projectAccountLeadRelations = new List<Project_Account_Lead_Relation__c>();
            List<Account_Lead__c> relatedAccountLeadsList = new List<Account_Lead__c>();

            if(project.Project_Account_Lead_Relations__r.size() > 0) {
                projectMap.put(project.id, project);
                for(Project_Account_Lead_Relation__c palr : project.Project_Account_Lead_Relations__r) {
                    projectAccountLeadRelations.add(palr);
                    Account_Lead__c accLead = new Account_Lead__c(
                        Id = palr.Account_Lead__c,
                        Name = palr.Account_Lead__r.Name
                    );
                    relatedAccountLeadsList.add(accLead);
                }
            }
            if(project.Project_Account_Relations__r.size() > 0) {
                projectMap.put(project.id, project);
                for(Project_Account_Relation__c par : project.Project_Account_Relations__r) {
                    projectAccountRelations.add(par);
                    Account acc = new Account(
                        Id = par.Account__c,
                        Name = par.Account__r.Name
                    );
                    relatedAccountsList.add(acc);
                }
            }
            if(projectMap.get(project.id) != null) {
                FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
                input.project = project;
                input.projectAccountRelations = projectAccountRelations;
                input.relatedAccountsList = relatedAccountsList;
                input.projectAccountLeadRelations = projectAccountLeadRelations;
                input.relatedAccountLeadsList = relatedAccountLeadsList;
                input.cleanseProjectFields = true;
                input.executeDuplicateCheck = false;
                inputVariables.add(input);
            }
        }

        //check that helper fields are empty
        System.assertEquals(null, projectMap.values()[0].Involved_Accounts_cleaned__c);
        System.assertEquals(null, projectMap.values()[0].Building_Owner_cleaned__c);
        System.assertEquals(null, projectMap.values()[0].Street_cleaned__c);
        System.assertEquals(null, projectMap.values()[0].House_Number_cleaned__c);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals('test,acn,test,acn,acn,', outputVariables[0].flowProject.Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', outputVariables[0].flowProject.Building_Owner_cleaned__c);
        System.assertEquals('test', outputVariables[0].flowProject.Street_cleaned__c);
        System.assertEquals('1', outputVariables[0].flowProject.House_Number_cleaned__c);
    }

    /**
     * Test InitDuplicateCheck method With New Project record (relevant for project creation flow)
     */
    @isTest
    private static void testInitDuplicateCheckWithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT Id, Name FROM Account LIMIT 2];
        List<Account_Lead__c> testAccountLeadList = [SELECT Id, Name FROM Account_Lead__c LIMIT 2];
    
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false);
        testProjectList[0].Street_cleaned__c = null;
        testProjectList[0].House_Number_cleaned__c = null;
        
        List<Project_Account_Relation__c> testPPARList = TESTDataFactory.createTestPARs(1, testAccountList[1], '1', testProjectList[0], false);
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '2', testProjectList[0], false));
        testPPARList.addAll(TESTDataFactory.createTestPARs(1, testAccountList[0], '1;3', testProjectList[0], false));

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = false;
        inputVariables.add(input);

        //check that helper fields are empty
        System.assertEquals(null, testProjectList[0].Involved_Accounts_cleaned__c);
        System.assertEquals(null, testProjectList[0].Building_Owner_cleaned__c);
        System.assertEquals(null, testProjectList[0].Street_cleaned__c);
        System.assertEquals(null, testProjectList[0].House_Number_cleaned__c);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals('test,acn,acn,', outputVariables[0].flowProject.Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', outputVariables[0].flowProject.Building_Owner_cleaned__c);
        System.assertEquals('test', outputVariables[0].flowProject.Street_cleaned__c);
        System.assertEquals('1', outputVariables[0].flowProject.House_Number_cleaned__c);
    }

    /**
     * Test InitDuplicateCheck method With New Project record including duplicate check (relevant for project creation flow)
     * Potential duplicate due to street and street number check
     */
    @isTest
    private static void testDuplicateCheck1WithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT 
                Id, 
                Name 
            FROM Account 
            LIMIT 2];
        
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = [SELECT 
                Id, 
                Name, 
                Project_Construction_Progress__c,
                Street__c,
                Project_Address__Street__s,
                Postal_Code__c,
                City__c,
                Total_Volume__c,
                Project_Construction_Start__c,
                Potential__c,
                Core_Source_System__c, 
                Project_Address__c, 
                Project_Address__Longitude__s, 
                Project_Address__Latitude__s, 
                Project_Address__PostalCode__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c,
                Involved_Accounts_cleaned__c,
                Building_Owner_cleaned__c,
                Building_Owner__c,
                Owner.Name,
                OwnerId,
                CreatedDate
            FROM Project__c 
            LIMIT 2];
        String projectId = testProjectList[0].Id;
        
        List<Project_Account_Relation__c> testPPARList = [SELECT 
                Id, 
                Account__c, 
                Project__c, 
                Account_Role__c 
            FROM Project_Account_Relation__c 
            WHERE Project__c = :projectId];

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = true;
        inputVariables.add(input);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals(true, outputVariables[0].potentialDuplicateProjectAvailable);
        System.assertEquals(2, outputVariables[0].potentialDuplicateProjectList.size());
    }

    /**
     * Test InitDuplicateCheck method With New Project record including duplicate check (relevant for project creation flow)
     * Potential duplicate due to building owner check
     */
    @isTest
    private static void testDuplicateCheck2WithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT 
                Id, 
                Name 
            FROM Account 
            LIMIT 2];
        
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = [SELECT 
                Id, 
                Name, 
                Project_Construction_Progress__c,
                Street__c,
                Project_Address__Street__s,
                Postal_Code__c,
                City__c,
                Total_Volume__c,
                Project_Construction_Start__c,
                Potential__c,
                Core_Source_System__c, 
                Project_Address__c, 
                Project_Address__Longitude__s, 
                Project_Address__Latitude__s, 
                Project_Address__PostalCode__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c,
                Involved_Accounts_cleaned__c,
                Building_Owner_cleaned__c,
                Building_Owner__c,
                Owner.Name,
                OwnerId,
                CreatedDate
            FROM Project__c 
            LIMIT 2];
        String projectId = testProjectList[0].Id;
        
        List<Project_Account_Relation__c> testPPARList = [SELECT 
                Id, 
                Account__c, 
                Project__c, 
                Account_Role__c 
            FROM Project_Account_Relation__c 
            WHERE Project__c = :projectId];

        testProjectList[0].House_Number_cleaned__c = '2';
        update testProjectList;

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = true;
        inputVariables.add(input);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals(true, outputVariables[0].potentialDuplicateProjectAvailable);
        System.assertEquals(2, outputVariables[0].potentialDuplicateProjectList.size());
    }

    /**
     * Test InitDuplicateCheck method With New Project record including duplicate check (relevant for project creation flow)
     * Potential duplicate due to involved accounts check
     */
    @isTest
    private static void testDuplicateCheck3WithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT 
                Id, 
                Name 
            FROM Account 
            LIMIT 2];
        
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = [SELECT 
                Id, 
                Name, 
                Project_Construction_Progress__c,
                Street__c,
                Project_Address__Street__s,
                Postal_Code__c,
                City__c,
                Total_Volume__c,
                Project_Construction_Start__c,
                Potential__c,
                Core_Source_System__c, 
                Project_Address__c, 
                Project_Address__Longitude__s, 
                Project_Address__Latitude__s, 
                Project_Address__PostalCode__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c,
                Involved_Accounts_cleaned__c,
                Building_Owner_cleaned__c,
                Building_Owner__c,
                Owner.Name,
                OwnerId,
                CreatedDate
            FROM Project__c 
            LIMIT 2];
        String projectId = testProjectList[0].Id;
        
        List<Project_Account_Relation__c> testPPARList = [SELECT 
                Id, 
                Account__c, 
                Project__c, 
                Account_Role__c 
            FROM Project_Account_Relation__c 
            WHERE Project__c = :projectId];

        testProjectList[0].House_Number_cleaned__c = '2';
        testProjectList[0].Building_Owner_cleaned__c = null;
        testProjectList[1].Building_Owner_cleaned__c = null;
        update testProjectList;

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = true;
        inputVariables.add(input);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals(true, outputVariables[0].potentialDuplicateProjectAvailable);
        System.assertEquals(2, outputVariables[0].potentialDuplicateProjectList.size());
    }

    /**
     * Test InitDuplicateCheck method With New Project record including duplicate check (relevant for project creation flow)
     * Potential duplicate due to geolocation
     */
    @isTest
    private static void testDuplicateCheck4WithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT 
                Id, 
                Name 
            FROM Account 
            LIMIT 2];
        
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = [SELECT 
                Id, 
                Name, 
                Project_Construction_Progress__c,
                Street__c,
                Project_Address__Street__s,
                Postal_Code__c,
                City__c,
                Total_Volume__c,
                Project_Construction_Start__c,
                Potential__c,
                Core_Source_System__c, 
                Project_Address__c, 
                Project_Address__Longitude__s, 
                Project_Address__Latitude__s, 
                Project_Address__PostalCode__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c,
                Involved_Accounts_cleaned__c,
                Building_Owner_cleaned__c,
                Building_Owner__c,
                Owner.Name,
                OwnerId,
                CreatedDate
            FROM Project__c 
            LIMIT 2];
        String projectId = testProjectList[0].Id;
        
        List<Project_Account_Relation__c> testPPARList = [SELECT 
                Id, 
                Account__c, 
                Project__c, 
                Account_Role__c 
            FROM Project_Account_Relation__c 
            WHERE Project__c = :projectId];

        testProjectList[0].Project_Address__Longitude__s = 1.000;
        testProjectList[0].Project_Address__Latitude__s = 1.000;
        testProjectList[1].Project_Address__Longitude__s = 1.000;
        testProjectList[1].Project_Address__Latitude__s = 1.000;
        update testProjectList;

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = true;
        inputVariables.add(input);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals(true, outputVariables[0].potentialDuplicateProjectAvailable);
        System.assertEquals(2, outputVariables[0].potentialDuplicateProjectList.size());
    }

    /**
     * Test InitDuplicateCheck method With New Project record including duplicate check (relevant for project creation flow)
     * No ootential duplicate
     */
    @isTest
    private static void testDuplicateCheck5WithNewProject() {
        List<FlowActionDuplicateCheck.InputVariables> inputVariables = new List<FlowActionDuplicateCheck.InputVariables>();
        List<FlowActionDuplicateCheck.OutputVariables> outputVariables = new List<FlowActionDuplicateCheck.OutputVariables>();
        List<Account> testAccountList = [SELECT 
                Id, 
                Name 
            FROM Account 
            LIMIT 2];
        
        // prepare data without inserting as in flow
        List<Project__c> testProjectList = [SELECT 
                Id, 
                Name, 
                Project_Construction_Progress__c,
                Street__c,
                Project_Address__Street__s,
                Postal_Code__c,
                City__c,
                Total_Volume__c,
                Project_Construction_Start__c,
                Potential__c,
                Core_Source_System__c, 
                Project_Address__c, 
                Project_Address__Longitude__s, 
                Project_Address__Latitude__s, 
                Project_Address__PostalCode__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c,
                Involved_Accounts_cleaned__c,
                Building_Owner_cleaned__c,
                Building_Owner__c,
                Owner.Name,
                OwnerId,
                CreatedDate
            FROM Project__c 
            LIMIT 2];
        String projectId = testProjectList[0].Id;
        
        List<Project_Account_Relation__c> testPPARList = [SELECT 
                Id, 
                Account__c, 
                Project__c, 
                Account_Role__c 
            FROM Project_Account_Relation__c 
            WHERE Project__c = :projectId];

        testProjectList[0].Street_cleaned__c =  null;
        testProjectList[1].Street_cleaned__c =  null;
        update testProjectList;

        FlowActionDuplicateCheck.InputVariables input = new FlowActionDuplicateCheck.InputVariables();
        input.project = testProjectList[0];
        input.projectAccountRelations = testPPARList;
        input.cleanseProjectFields = true;
        input.executeDuplicateCheck = true;
        inputVariables.add(input);

        Test.startTest();
            outputVariables = FlowActionDuplicateCheck.initDuplicateCheck(inputVariables);
        Test.stopTest();

        //verify results
        System.assertEquals(false, outputVariables[0].potentialDuplicateProjectAvailable);
        System.assertEquals(0, outputVariables[0].potentialDuplicateProjectList.size());
    }
}