force-app/main/default/objects/Account/fields/Core_Email__c.field-meta.xml
<CustomField>
    <fullName>Core_Email__c</fullName>
    <description>1. Integration relevant (Grace)
2. CORE
3.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Relation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Relation__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Customer Relation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ibau_Id__c.field-meta.xml
<CustomField>
    <fullName>Ibau_Id__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZBM
3. Used to map a Salesforce Account to an Account in BIS to be able to connect them to Projects. Set by migration or via Flow ??????</description>
    <externalId>true</externalId>
    <label>Ibau Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Infobau_Id__c.field-meta.xml
<CustomField>
    <fullName>Infobau_Id__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZBM
3. Used to map a Salesforce Account to an Account in BIS to be able to connect them to Projects. Set by migration or via Flow ??????</description>
    <externalId>true</externalId>
    <label>Infobau Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/ZR_Standard_Account_Prospect.recordType-meta.xml
<RecordType>
    <fullName>ZR_Standard_Account_Prospect</fullName>
    <active>true</active>
    <description>Record type for accounts with type prospect</description>
    <label>Account Prospect</label>
</RecordType>

force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Lead__c/fields/Ibau_Id__c.field-meta.xml
<CustomField>
    <fullName>Ibau_Id__c</fullName>
    <description>1. Integration relevant (ibau)
2. ZR
3. SF-1155</description>
    <externalId>true</externalId>
    <label>Ibau Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Lead__c/fields/Infobau_Id__c.field-meta.xml
<CustomField>
    <fullName>Infobau_Id__c</fullName>
    <description>1. Integration relevant (infobau)
2. ZR
3. SF-1155</description>
    <externalId>true</externalId>
    <label>Infobau Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/BIS_Project_Import_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BIS Project Import Config</label>
</CustomObject>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Error_Emails__c.field-meta.xml
<CustomField>
    <fullName>Error_Emails__c</fullName>
    <description>Comma separated list of email addresses to sent out error notifications.</description>
    <inlineHelpText>Comma separated list of email addresses to sent out error notifications.</inlineHelpText>
    <label>Error Emails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Filter_JSON_Ibau_DE__c.field-meta.xml
<CustomField>
    <fullName>Filter_JSON_Ibau_DE__c</fullName>
    <description>Optional project request parameter to filter for specific projects.
Example: {&quot;project$$attributes$$town&quot;: &quot;Leipzig&quot;}</description>
    <inlineHelpText>Optional project request parameter to filter for specific projects.
Example: {&quot;project$$attributes$$town&quot;: &quot;Leipzig&quot;}</inlineHelpText>
    <label>Filter JSON Ibau DE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Filter_JSON_Infobau__c.field-meta.xml
<CustomField>
    <fullName>Filter_JSON_Infobau__c</fullName>
    <description>Optional project request parameter to filter for specific projects.
Example: {&quot;project$$attributes$$town&quot;: &quot;Leipzig&quot;}</description>
    <inlineHelpText>Optional project request parameter to filter for specific projects.
Example: {&quot;project$$attributes$$town&quot;: &quot;Leipzig&quot;}</inlineHelpText>
    <label>Filter JSON Infobau</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Include_Involved_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Include_Involved_Accounts__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field used in Apex class BISProjectImport to either include the handling of involved Accounts to create matching Account Leads, Project Account Relations and Project Account Lead Relations or not.</description>
    <label>Include Involved Accounts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Page_Size__c</fullName>
    <description>The number of projects to be requested per page (max: 250)</description>
    <inlineHelpText>The number of projects to be requested per page (max: 250)</inlineHelpText>
    <label>Page Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BIS_Project_Import_Config__c/fields/Project_Construction_Start_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Start_Placeholder__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-1345 Projekt ohne Baubeginn kann nicht mit Potenzial versehen werden</description>
    <inlineHelpText>Enter a placeholder that will be used for projects with neither a start and submission date</inlineHelpText>
    <label>Project Construction Start Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Core_Apex_Class__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Name of the Apex Class causing the error</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Core_Error_Message__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Core_Exception_Type__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Core_Stack_Trace__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Relevant for errors based on apex code</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Technical_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Core_Technical_Error_Message__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Technical Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration irrelevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-647. Stores the unique external ID including prefix for ibau and infobau.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/iBau_ID__c.field-meta.xml
<CustomField>
    <fullName>iBau_ID__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-647. Stores the second available ibau-ID for later purposes.</description>
    <label>iBau ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_End__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_End__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Start__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZRD
3. SF-1155</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Leads</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Submission_Result__c/Submission_Result__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-261</description>
    <label>Submissionsergebnis</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Submission Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissionsergebnisse</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Submission_Result__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-647</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Submission_Result__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant  (BIS)
2. ZRD
3. SF-261</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Submission Results</relationshipLabel>
    <relationshipName>Submission_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Submission_Result__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1. Integration relevant (BIS)
2. ZRD
3. SF-261</description>
    <label>Winner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BISProjectImportTest.cls
/**
 * Test class for "BISProjectImport".
 * 
 * @author	rene.pienkoss@accenture.com
 *
 * @version 2022-01-20	rene.pienkoss@accenture.com		creation
 * @version 2023-09-08  miriam.ida.tyroller@accenture   added testing for involved accounts
 * @version 2023-10-30  isabella.moos@accenture         modify test methods for new projekt account (lead) relations, as they cannot be tested in this context due to chained queueable jobs limit in test classes
 */
@IsTest(SeeAllData=false)
public with sharing class BISProjectImportTest {

    public final static String IBAU_ID_TESTING = '123';
    public final static String INFOBAU_ID_TESTING = '345';
    public final static String INFOBAU_DOUBLE_ID_TESTING = '999';
    public final static String IBAU_DOUBLE_ID_TESTING = '888';
    
    /**
     * Create test data
     */
    @TestSetup
    public static void createTestData() {
        // create custom setting
        BIS_Project_Import_Config__c bisConf = new BIS_Project_Import_Config__c(SetupOwnerId = UserInfo.getOrganizationId());
        bisConf.Page_Size__c = 100;
        bisConf.Filter_JSON_Ibau_DE__c = '{"project$$attributes$$town": "Düsseldorf"}';
        bisConf.Filter_JSON_Infobau__c = '{"project$$attributes$$town": "Weiden"}';
        bisConf.Error_Emails__c = 'miriam.ida.tyroller@accenture.com';
        bisConf.Project_Construction_Start_Placeholder__c = '1999-09-09T23:00:00.000Z';
        bisConf.Include_Involved_Accounts__c = true;
        insert bisConf;

        Id rt_Propect = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ZR_Standard_Account_Prospect').getRecordTypeId();
        Account acc1 = new Account(Name = 'ACN Test Account BIS Import 1');
        acc1.RecordTypeId = rt_Propect;
        acc1.Phone = '+4911223344';
        acc1.Customer_Relation__c = 'Customer';
        acc1.Core_Email__c = 'testacc@BISImport.com';
        acc1.BillingStreet = 'Test Street 1';
        acc1.BillingCity = 'Jena';
        acc1.BillingPostalCode = '07745';
        acc1.BillingCountryCode = 'DE';
        acc1.Infobau_Id__c = INFOBAU_ID_TESTING;
        acc1.Ibau_Id__c = IBAU_ID_TESTING;
        insert acc1;

        Account acc2 = new Account(Name = 'ACN Test Account BIS Import 2');
        acc2.RecordTypeId = rt_Propect;
        acc2.Phone = '+4998765498';
        acc2.Customer_Relation__c = 'Customer';
        acc2.Core_Email__c = 'testacc@test.com';
        acc2.BillingStreet = 'Test Street 9';
        acc2.BillingCity = 'City';
        acc2.BillingPostalCode = '12345';
        acc2.BillingCountryCode = 'DE';
        acc2.Infobau_Id__c = INFOBAU_DOUBLE_ID_TESTING;
        acc2.Ibau_Id__c = IBAU_DOUBLE_ID_TESTING;
        insert acc2;

        Account acc3 = new Account(Name = 'ACN Test Account BIS Import 3');
        acc3.RecordTypeId = rt_Propect;
        acc3.Phone = '+4956789677';
        acc3.Customer_Relation__c = 'Customer';
        acc3.Core_Email__c = 'testacc@mail.com';
        acc3.BillingStreet = 'Test Street 3';
        acc3.BillingCity = 'Town';
        acc3.BillingPostalCode = '54321';
        acc3.BillingCountryCode = 'DE';
        acc3.Infobau_Id__c = INFOBAU_DOUBLE_ID_TESTING;
        acc3.Ibau_Id__c = IBAU_DOUBLE_ID_TESTING;
        insert acc3;
    }

    /**
     * test_projectImport_ibau_de
     */
    @IsTest
    public static void test_projectImport_ibau_de() {
        String context = BISProjectImport.CONTEXT_IBAU_DE;

        // ensure that timestamp of last update is null
        BIS_Project_Import_Config__c conf = BIS_Project_Import_Config__c.getOrgDefaults();
        Decimal lastImportTimestamp = (Decimal) conf.get(BISProjectImport.timestampFieldNamesByContext.get(context));
        System.assertEquals(null, lastImportTimestamp);

        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(context);
        System.enqueueJob(projectImport);
        
        Test.stopTest();

        // validate results
        // check if project records has been created
        List<Project__c> proList = [SELECT Id, Exact_Source__c, External_ID__c FROM Project__c];
        System.assertEquals(1, proList.size());
        System.assertEquals('iBau', proList[0].Exact_Source__c);
        System.assertEquals('ibau_1714447', proList[0].External_ID__c);

        //assert involved Accounts relations were created successfully
        assertAccountLeads(1);
        //assertProjectAccountRelations(3);
        //assertProjectAccountLeadRelations(1);
        //assertDoubleIbauProjectAccountRelations(2,IBAU_DOUBLE_ID_TESTING);

        // check if timestamp of last update is updated
        conf = BIS_Project_Import_Config__c.getOrgDefaults();
        lastImportTimestamp = (Decimal) conf.get(BISProjectImport.timestampFieldNamesByContext.get(context));
        System.assertNotEquals(null, lastImportTimestamp);
    }

    /**
     * test_projectImport_ibau_de_error
     */
    @IsTest
    public static void test_projectImport_ibau_de_error() {
        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(BISProjectImport.CONTEXT_IBAU_DE);
        projectImport.testError = true;
        System.enqueueJob(projectImport);
        
        Test.stopTest();

        // validate results
        List<Project__c> proList = [SELECT Id, Exact_Source__c, External_ID__c FROM Project__c];
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = : BISProjectImport.CLASSNAME];
        
        System.assertEquals(0, proList.size());
        System.assertEquals(1, errorLogs.size());
    }

    /**
     * test_projectImport_ibau_de_retry
     */
    @IsTest
    public static void test_projectImport_ibau_de_retry() {
        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(BISProjectImport.CONTEXT_IBAU_DE);
        projectImport.testRetry = true;
        System.enqueueJob(projectImport);
        
        Test.stopTest();

        // validate results
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = : BISProjectImport.CLASSNAME];
        System.assertEquals(0, errorLogs.size());
    }

    /**
     * test_projectImport_infobau
     */
    @IsTest
    public static void test_projectImport_infobau() {
        String context = BISProjectImport.CONTEXT_INFOBAU;

        // ensure that timestamp of last update is null
        BIS_Project_Import_Config__c conf = BIS_Project_Import_Config__c.getOrgDefaults();
        Decimal lastImportTimestamp = (Decimal) conf.get(BISProjectImport.timestampFieldNamesByContext.get(context));
        System.assertEquals(null, lastImportTimestamp);

        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(context);
        System.enqueueJob(projectImport);
        
        Test.stopTest();

        // validate results
        // check if project records has been created
        List<Project__c> proList = [SELECT Id, Exact_Source__c, External_ID__c, Project_Construction_Start__c, Project_Construction_End__c,
                                        (SELECT Id, External_ID__c, Winner__c FROM Submission_Results__r) 
                                    FROM Project__c];
        System.assertEquals(1, proList.size());
        System.assertEquals('infoBau', proList[0].Exact_Source__c);
        System.assertEquals('infobau_12345', proList[0].External_ID__c);

        // submission results
        System.assertEquals(4, proList[0].Submission_Results__r.size());
        for (Submission_Result__c sr : proList[0].Submission_Results__r) {
            System.debug('sr.External_ID__c: ' + sr.External_ID__c);
            if (sr.External_ID__c == proList[0].External_ID__c+'_6000210') {
                System.assertEquals(true, sr.Winner__c);
            }
            else {
                System.assertEquals(false, sr.Winner__c);
            }
        }

        //assert involved Accounts relations were created successfully
        assertAccountLeads(2);
        //assertProjectAccountRelations(3);
        //assertProjectAccountLeadRelations(2);
        //assertDoubleInfobauProjectAccountRelations(2,INFOBAU_DOUBLE_ID_TESTING);


        // check if timestamp of last update is updated
        conf = BIS_Project_Import_Config__c.getOrgDefaults();
        lastImportTimestamp = (Decimal) conf.get(BISProjectImport.timestampFieldNamesByContext.get(context));
        System.assertNotEquals(null, lastImportTimestamp);
    }

    /**
     * test_projectImport_infobau_error
     */
    @IsTest
    public static void test_projectImport_infobau_error() {
        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(BISProjectImport.CONTEXT_INFOBAU);
        projectImport.testError = true;
        System.enqueueJob(projectImport);
        
        Test.stopTest();

        // validate results
        List<Project__c> proList = [SELECT Id, Exact_Source__c, External_ID__c, 
                                        (SELECT Id, External_ID__c, Winner__c FROM Submission_Results__r) 
                                    FROM Project__c];
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c, Core_Error_Message__c,Core_Exception_Type__c, Core_Stack_Trace__c, Core_Technical_Error_Message__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = : BISProjectImport.CLASSNAME];

        System.assertEquals(1, proList.size());
        System.assertEquals(1, errorLogs.size());
    }

    /**
     * test_projectImport_errorlog
     */
    @IsTest
    public static void test_projectImport_errorlog() {
        Test.startTest();

        BISProjectImport projectImport = new BISProjectImport(BISProjectImport.CONTEXT_INFOBAU);
        projectImport.createErrorLog('Test Error');
        
        Test.stopTest();

        // validate results
        System.assertEquals(1, projectImport.errorLogs.size());
    }

    /**
     * test_BISIbauImportScheduler
     */
    @IsTest
    public static void test_BISIbauImportScheduler() {
        Test.startTest();
        
		// Schedule the test job
		String CRON_EXP = '0 0 0 3 9 ? 2080';
		String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BISIbauImportScheduler());
		// Get the information from the CronTrigger API object
        List<CronTrigger> ctList = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        
        Test.stopTest();
        
        // validate results
        System.assert(!ctList.isEmpty());
    }

    /**
     * test_BISInfobauImportScheduler
     */
    @IsTest
    public static void test_BISInfobauImportScheduler() {
        Test.startTest();
        
		// Schedule the test job
		String CRON_EXP = '0 0 0 3 9 ? 2080';
		String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BISInfobauImportScheduler());
		// Get the information from the CronTrigger API object
        List<CronTrigger> ctList = [SELECT id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        
        Test.stopTest();
        
        // validate results
        System.assert(!ctList.isEmpty());
    }

    

    public static void assertAccountLeads(Integer count){
        List<Account_Lead__c> accountLeadList = [SELECT Id FROM Account_Lead__c];
        System.assertEquals(count,accountLeadList.size());
    }

    public static void assertProjectAccountRelations(Integer count){
        List<Project_Account_Relation__c> projAccRelationList = [SELECT Id FROM Project_Account_Relation__c];
        System.assertEquals(count,projAccRelationList.size());
    }

    public static void assertDoubleInfobauProjectAccountRelations(Integer count, String InfobauID){
        List<Project_Account_Relation__c> projAccRelationList = [SELECT Id, Account__r.Infobau_Id__c FROM Project_Account_Relation__c WHERE Account__r.Infobau_Id__c = : InfobauID];
        System.assertEquals(count,projAccRelationList.size());
    }

    public static void assertDoubleIbauProjectAccountRelations(Integer count, String IbauID){
        List<Project_Account_Relation__c> projAccRelationList = [SELECT Id, Account__r.Ibau_Id__c FROM Project_Account_Relation__c WHERE Account__r.Ibau_Id__c = : IbauID];
        System.assertEquals(count,projAccRelationList.size());
    }

    public static void assertProjectAccountLeadRelations(Integer count){
        List<Project_Account_Lead_Relation__c> projAccLeadRelationList = [SELECT Id FROM Project_Account_Lead_Relation__c];
        System.assertEquals(count,projAccLeadRelationList.size());
    }

}