force-app/main/default/objects/Account/fields/Core_Email__c.field-meta.xml
<CustomField>
    <fullName>Core_Email__c</fullName>
    <description>1. Integration relevant (Grace)
2. CORE
3.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-763</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Relation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Relation__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Customer Relation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Lead__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account_Lead__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (XFAIR)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration irrelevant
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/House_Number_cleaned__c.field-meta.xml
<CustomField>
    <fullName>House_Number_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned House Number data</description>
    <label>House Number (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_End__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_End__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Street_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Street_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned Street data</description>
    <label>Street (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Lead__c.field-meta.xml
<CustomField>
    <fullName>Account_Lead__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <referenceTo>Account_Lead__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant
2. ZR
3. SF-1155</description>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZRD
3. SF-1155</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Leads</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/Project_Account_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-141</description>
    <label>Projekt Account Beziehung</label>
    <nameField>
        <displayFormat>PAR-{00000}</displayFormat>
        <label>Project Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Account Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Account Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Involved Accounts</relationshipLabel>
    <relationshipName>Project_Account_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Account_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Architect</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Bidder</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Building Contractor</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Building Owner</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Consultant</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Further Participants</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>General Constructor</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Operating Firm</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Operator</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Planer</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Planer and Engineers</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Project Controller</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Project Developer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Property Surveillance</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Tenant</label>
    </customValue>
    <masterLabel>Account Role</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>19</fullName>
        <label>Account Manager Recommendation</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Campaign</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Call</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Construction Information Systems</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Construction Site Visits</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Customer Call</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Customer Recommendation</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Customer Visit/ Customer information</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Email Mailing</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Lead Purchase</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Postal Mailing</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Public announcement - Building lot</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>Public announcement - Trade lot</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Request</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Trade Show</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Webpages / Portals</label>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TESTDataFactory.cls
/**
 * Test data factory providing methods to create data for test classes
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-20  isabella.moos@accenture.com     creation
 */
@isTest
public class TESTDataFactory {
    /**
     * Return List<Account> of test accounts 
     *
     * @param numOfRecords          number of records to be returned
     * @param recordTypeDevName     record type developer name
     * @param doInsert              insert the created records into database
     *
     * @return List<Account>
     */
    public static List<Account> createTestAccounts(Integer numOfRecords, String recordTypeDevName, Boolean doInsert) {
        List<Account> testAccountList = new List<Account>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(recordTypeDevName).getRecordTypeId();

        for(Integer i = 0; i < numOfRecords; i++) {
            Account testAccount = new Account(
                Name = 'ACN Test Account' + i,
                RecordTypeId = recordTypeId,
                Phone = '+49123456780',
                Customer_Relation__c = 'Customer',
                Core_Email__c = 'testacc@accenture.com',
                BillingStreet = 'Test Street ' + i,
                BillingCity = 'Jena',
                BillingPostalCode = '07745',
                BillingCountryCode = 'DE'
            );
            testAccountList.add(testAccount);
        }

        if (doInsert) {
            insert testAccountList;
        }

        return testAccountList;
    }

    /**
     * Return List<Account_Lead__c> of test account leads 
     *
     * @param numOfRecords          number of records to be returned
     * @param recordTypeDevName     record type developer name
     * @param doInsert              insert the created records into database
     *
     * @return List<Account_Lead__c>
     */
    public static List<Account_Lead__c> createTestAccountLeads(Integer numOfRecords, String recordTypeDevName, Boolean doInsert) {
        List<Account_Lead__c> testAccountLeadList = new List<Account_Lead__c>();
        Id recordTypeId = Schema.SObjectType.Account_Lead__c.getRecordTypeInfosByDeveloperName().get(recordTypeDevName).getRecordTypeId();

        for(Integer i = 0; i < numOfRecords; i++) {
            Account_Lead__c testAccountLead = new Account_Lead__c(
                Name = 'ACN Test Account Lead' + i,
                RecordTypeId = recordTypeId,
                Phone__c = '+49123456780',
                Email__c = 'testacc@accenture.com',
                Address__Street__s = 'Test Street ' + i,
                Address__City__s = 'Jena',
                Address__PostalCode__s = '07745',
                Address__CountryCode__s = 'DE'
            );
            testAccountLeadList.add(testAccountLead);
        }

        if (doInsert) {
            insert testAccountLeadList;
        }

        return testAccountLeadList;
    }

    /**
     * Return List<Project__c> of test projectss 
     *
     * @param numOfRecords          number of records to be returned
     * @param recordTypeDevName     record type developer name
     * @param doInsert              insert the created records into database
     *
     * @return List<Project__c>
     */
    public static List<Project__c> createTestIBauProjects(Integer numOfRecords, String recordTypeDevName, Boolean doInsert) {
        List<Project__c> testProjectList = new List<Project__c>();
        Id recordTypeId = Schema.SObjectType.Project__c.getRecordTypeInfosByDeveloperName().get(recordTypeDevName).getRecordTypeId();

        for(Integer i = 0; i < numOfRecords; i++) {
            Project__c testProject = new Project__c(
                Name = 'Test Ibau Project ' + i,
                RecordTypeId = recordTypeId,
                Project_Address__CountryCode__s = 'DE',
                Project_Address__City__s = 'TestCity',
                Project_Address__PostalCode__s = '12345',
                Project_Address__Street__s = 'Test Street 1',
                Street_cleaned__c = 'test',
                House_Number_cleaned__c = '1',
                Core_Source_System__c = 'BIS',
                Project_Source__c = '29',
                Project_Construction_Progress__c = '7',
                Exact_Source__c = 'iBau',
                Project_Construction_End__c = Date.today().addMonths(-12),
                Active__c = true
            );
            testProjectList.add(testProject);
        }

        if (doInsert) {
            insert testProjectList;
        }

        return testProjectList;
    }

    /**
     * Return List<Project_Account_Relation__c> of test Project Account Relations 
     *
     * @param numOfRecords      number of records to be returned
     * @param relatedAccount    account record that will be linked to new Project_Account_Relation__c records
     * @param accountRole       role of account linked to new Project_Account_Relation__c records
     * @param relatedProject    project record that will be linked to new Project_Account_Relation__c records
     * @param doInsert          insert the created records into database
     *
     * @return List<Project__c>
     */
    public static List<Project_Account_Relation__c> createTestPARs(Integer numOfRecords, Account relatedAccount, String accountRole, Project__c relatedProject, Boolean doInsert) {
        List<Project_Account_Relation__c> testPARList = new List<Project_Account_Relation__c>();

        for(Integer i = 0; i < numOfRecords; i++) {
            Project_Account_Relation__c testPAR = new Project_Account_Relation__c(
                Account__c = relatedAccount.Id,
                Account_Role__c = accountRole,
                Project__c = relatedProject.Id
            );
            testPARList.add(testPAR);
        }

        if (doInsert) {
            insert testPARList;
        }

        return testPARList;
    }

    /**
     * Return List<Project_Account_Lead_Relation__c> of test Project Account Relations 
     *
     * @param numOfRecords          number of records to be returned
     * @param relatedAccountLead    account record that will be linked to new Project_Account_Lead_Relation__c records
     * @param accountRole           role of account linked to new Project_Account_Lead_Relation__c records
     * @param relatedProject        project record that will be linked to new Project_Account_Lead_Relation__c records
     * @param doInsert              insert the created records into database
     *
     * @return List<Project__c>
     */
    public static List<Project_Account_Lead_Relation__c> createTestPALRs(Integer numOfRecords, Account_Lead__c relatedAccountLead, String accountRole, Project__c relatedProject, Boolean doInsert) {
        List<Project_Account_Lead_Relation__c> testPALRList = new List<Project_Account_Lead_Relation__c>();

        for(Integer i = 0; i < numOfRecords; i++) {
            Project_Account_Lead_Relation__c testPALR = new Project_Account_Lead_Relation__c(
                Account_Lead__c = relatedAccountLead.Id,
                Account_Role__c = accountRole,
                Project__c = relatedProject.Id
            );
            testPALRList.add(testPALR);
        }

        if (doInsert) {
            insert testPALRList;
        }

        return testPALRList;
    }
}