force-app/main/default/objects/Account/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-763</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Name2__c.field-meta.xml
<CustomField>
    <fullName>Name2__c</fullName>
    <description>1. Integration relevant (Grace)
2. ZR
3.</description>
    <label>Name 2</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Save_without_Email__c.field-meta.xml
<CustomField>
    <fullName>Save_without_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>1. Not integration relevant
2. ZR
3. Use this field to disable the validation rule that is set on the Email address field to save an account without an email address</description>
    <inlineHelpText>If you want to save an Account without an Email address please check this checkbox.</inlineHelpText>
    <label>Save without Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>1. Integration relevant (Grace)
2. ZRD.
3.</description>
    <label>Overall Project Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Core_Source_System__c.field-meta.xml
<CustomField>
    <fullName>Core_Source_System__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Exact_Source__c.field-meta.xml
<CustomField>
    <fullName>Exact_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Exact Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Exact_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Progress__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project-/ Construction Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Discussion</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pre Planning</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planning</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Shortly before Start</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Implementation</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Shortly before Completion / Completion</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Construction_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Construction_Start__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZRD
3.</description>
    <label>Project-/ Construction Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Source__c.field-meta.xml
<CustomField>
    <fullName>Project_Source__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Project Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Volume__c.field-meta.xml
<CustomField>
    <fullName>Total_Volume__c</fullName>
    <description>1. Integration relevant (BIS)
2. ZR
3.</description>
    <label>Total Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Exact_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>beDirect</fullName>
    </customValue>
    <customValue>
        <fullName>CAT Rental Store</fullName>
    </customValue>
    <customValue>
        <fullName>Kundenschnittstelle</fullName>
        <label>Customer Interface Portal</label>
    </customValue>
    <customValue>
        <fullName>DTAD</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>iBau</fullName>
        <label>ibau</label>
    </customValue>
    <customValue>
        <fullName>infoBau</fullName>
        <label>infobau</label>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Klickrent</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Magazine</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Online Advertisement / Banner</fullName>
    </customValue>
    <customValue>
        <fullName>Betreibermodell</fullName>
        <label>Operator Model</label>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>RentX</fullName>
    </customValue>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Waste-Management</fullName>
    </customValue>
    <customValue>
        <fullName>Xing</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Baumaschine</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Group</fullName>
    </customValue>
    <customValue>
        <fullName>Zeppelin Rental</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Accomodation configurator</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Energy portal</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Insite 3.0</fullName>
    </customValue>
    <customValue>
        <fullName>ZRD - Online Rental</fullName>
    </customValue>
    <masterLabel>Exact Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>19</fullName>
        <label>Account Manager Recommendation</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Campaign</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>Call</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Construction Information Systems</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Construction Site Visits</label>
    </customValue>
    <customValue>
        <fullName>34</fullName>
        <label>Customer Call</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>Customer Recommendation</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Customer Visit/ Customer information</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>Email Mailing</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Event</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Lead Purchase</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>36</fullName>
        <label>Postal Mailing</label>
    </customValue>
    <customValue>
        <fullName>37</fullName>
        <label>Public announcement - Building lot</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>Public announcement - Trade lot</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Request</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>Social Media</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Trade Show</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>Webpages / Portals</label>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BIS</fullName>
    </customValue>
    <customValue>
        <fullName>BPS</fullName>
    </customValue>
    <customValue>
        <fullName>Grace</fullName>
    </customValue>
    <customValue>
        <fullName>iTWO</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>XFAIR</fullName>
    </customValue>
    <description>1. Integration relevant (GRACE, XFAIR)
2. ZRD
3.</description>
    <masterLabel>Source System</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LWCHandlerMapCompTest.cls
/**
 * SF-1134:  test class for LWCHandlerMapComp
 * 
 * @author  miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-10-09  miriam.ida.tyroller       creation
 */
@IsTest
public with sharing class LWCHandlerMapCompTest {
    
    @TestSetup
    public static void createTestData(){
        Date todayDate = Date.today();

        // ibau project with total volume
        Project__c project1 = new Project__c();
        project1.Name = 'Test Project 1';
        project1.Project_Address__CountryCode__s = 'DE';
        project1.Project_Address__City__s = 'TestCity';
        project1.Project_Address__PostalCode__s = '12345';
        project1.Project_Address__Street__s = 'Test Street';
        project1.Core_Source_System__c = 'BIS';
        project1.Project_Source__c = '29';
        project1.Project_Construction_Progress__c = '7';
        project1.Exact_Source__c = 'iBau';
        project1.Project_Construction_Start__c = todayDate;
        project1.Total_Volume__c = 2000.00;
        project1.Active__c = true;
        insert project1;

        // infobau project with total volume
        Project__c project2 = new Project__c();
        project2.Name = 'Test Project 2';
        project2.Project_Address__CountryCode__s = 'DE';
        project2.Project_Address__City__s = 'Test Town';
        project2.Project_Address__PostalCode__s = '99999';
        project2.Project_Address__Street__s = 'Test Street';
        project2.Core_Source_System__c = 'BIS';
        project2.Project_Source__c = '29';
        project2.Project_Construction_Progress__c = '7';
        project2.Exact_Source__c = 'infoBau';
        project1.Project_Construction_Start__c = todayDate;
        project2.Total_Volume__c = 3000.00;
        project2.Active__c = true;
        insert project2;

        // ibau Project without total volume
        Project__c project3 = new Project__c();
        project3.Name = 'Test Project 3';
        project3.Project_Address__CountryCode__s = 'DE';
        project3.Project_Address__StateCode__s = 'BY';
        project3.Project_Address__City__s = 'TestCity';
        project3.Project_Address__PostalCode__s = '88888';
        project3.Project_Address__Street__s = 'Test Street';
        project3.Core_Source_System__c = 'BIS';
        project3.Project_Source__c = '29';
        project3.Project_Construction_Progress__c = '7';
        project3.Exact_Source__c = 'iBau';
        project1.Project_Construction_Start__c = todayDate;
        project3.Active__c = true;
        insert project3;


        Account acc1 = new Account(Name = 'Test Acc 1');
        acc1.Save_without_Email__c = true;
        acc1.BillingCity = 'Test Town';
        acc1.BillingPostalCode = '54321';
        acc1.BillingStreet = 'Test Street 3';
        insert acc1;

        Account acc2 = new Account(Name = 'Test Acc 2');
        acc2.Name2__c = 'Test Acc 2 Name 2';
        acc2.Save_without_Email__c = true;
        acc2.BillingCity = 'Test City';
        acc2.BillingPostalCode = '12345';
        acc2.BillingStateCode = 'BY';
        acc2.BillingStreet = 'Test Street 1';
        insert acc2;

        Account acc3 = new Account(Name = 'Test Acc 3');
        acc3.Save_without_Email__c = true;
        acc3.BillingCity = 'Test Test';
        acc3.BillingPostalCode = '99999';
        acc3.BillingStreet = 'Test Street 9';
        insert acc3;

    }

    @IsTest
    public static void test_queryMapDataProjects() {
        String listViewId = 'help';

        Test.startTest();
            List<LWCHandlerMapComp.MapMarker> projectList = LWCHandlerMapComp.queryMapData(listViewId, 'www.Project.de');
        Test.stopTest();

        System.assertEquals(3,projectList.size());
    }

    @IsTest
    public static void test_queryMapDataAccounts() {
        String listViewId = 'help';

        Test.startTest();
            List<LWCHandlerMapComp.MapMarker> accountList = LWCHandlerMapComp.queryMapData(listViewId, 'www.Account.de');
        Test.stopTest();

        System.assertEquals(3,accountList.size());
    }

    @IsTest
    public static void test_queryUserListViewsProjects() {

        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs (thisUser) {
            List<ListView> testList = [SELECT Id, Name FROM ListView WHERE SobjectType = 'Project__c'];

            Test.startTest();
                List<ListView> listViewList = LWCHandlerMapComp.queryUserListViews('www.Project.de');
            Test.stopTest();

        System.assertEquals(testList.size(),listViewList.size());

        }
    }

    @IsTest
    public static void test_queryUserListViewsAccounts() {

        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs (thisUser) {
            List<ListView> testList = [SELECT Id, Name FROM ListView WHERE SobjectType = 'Account'];
        

            Test.startTest();
                List<ListView> listViewList = LWCHandlerMapComp.queryUserListViews('www.Account.de');
            Test.stopTest();

        System.assertEquals(testList.size(),listViewList.size());
        }
    }

    

}