force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/Project_Team__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant
2. ZRD
3. SF-641</description>
    <label>Projekt Team - Mitglied</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projekt Team - Mitglieder</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant
2. ZRD.
3.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team</relationshipLabel>
    <relationshipName>Project_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <description>1. Integration relevant
2. ZRD
3.</description>
    <label>Team Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Branch_Manager</fullName>
                <isActive>false</isActive>
                <label>Branch Manager</label>
            </value>
            <value>
                <fullName>Calculator</fullName>
            </value>
            <value>
                <fullName>Commercial_Clerk</fullName>
                <isActive>false</isActive>
                <label>Commercial Clerk</label>
            </value>
            <value>
                <fullName>Commercial_Manager</fullName>
                <label>Commercial Manager</label>
            </value>
            <value>
                <fullName>Consultant Logistic and Sales</fullName>
            </value>
            <value>
                <fullName>Contact_Business_Administration</fullName>
                <label>Contact - Business Administration</label>
            </value>
            <value>
                <fullName>Controlling</fullName>
                <isActive>false</isActive>
                <label>Controlling</label>
            </value>
            <value>
                <fullName>Deputy_Director_of_Rental_Office</fullName>
                <label>Deputy Director of Rental Office</label>
            </value>
            <value>
                <fullName>Deputy_Head_of_Region</fullName>
                <label>Deputy Head of Region</label>
            </value>
            <value>
                <fullName>Director_of_Rental_Office</fullName>
                <label>Director of Rental Office</label>
            </value>
            <value>
                <fullName>Head_of_Construction</fullName>
                <isActive>false</isActive>
                <label>Head of Construction</label>
            </value>
            <value>
                <fullName>Head_of_Division</fullName>
                <label>Head of Division</label>
            </value>
            <value>
                <fullName>Head_of_Energy_Trade</fullName>
                <label>Head of Energy Trade</label>
            </value>
            <value>
                <fullName>Head_of_industrial_equipment</fullName>
                <label>Head of industrial equipment</label>
            </value>
            <value>
                <fullName>Head_of_operating_platforms_elevators_and_fork_lift_trucks</fullName>
                <label>Head of operating platforms elevators and fork lift trucks</label>
            </value>
            <value>
                <fullName>Head_of_Operation</fullName>
                <isActive>false</isActive>
                <label>Head of Operation</label>
            </value>
            <value>
                <fullName>Head_of_Region</fullName>
                <label>Head of Region</label>
            </value>
            <value>
                <fullName>Head_of_Sales</fullName>
                <label>Head of Sales</label>
            </value>
            <value>
                <fullName>Head_of_Service</fullName>
                <isActive>false</isActive>
                <label>Head of Service</label>
            </value>
            <value>
                <fullName>Head_of_Standard</fullName>
                <isActive>false</isActive>
                <label>Head of Standard</label>
            </value>
            <value>
                <fullName>Head_of_Traffic_Telematics</fullName>
                <isActive>false</isActive>
                <label>Head of Traffic Telematics</label>
            </value>
            <value>
                <fullName>Head_of_vehicles</fullName>
                <label>Head of vehicles</label>
            </value>
            <value>
                <fullName>Inside_Sales_Customer_Consultant_Rental_Electric_and_Energy_EE</fullName>
                <label>Inside Sales/ Customer Consultant EEB (EKW)</label>
            </value>
            <value>
                <fullName>Inside Sales/ Customer Consultant Electricity and Climate</fullName>
            </value>
            <value>
                <fullName>Inside_Sales_Customer_Consultant_Rental_Construction_Logistic_LCM</fullName>
                <label>Inside Sales/ Customer Consultant LC&amp;M</label>
            </value>
            <value>
                <fullName>Inside_Sales_Customer_Consultant_Rental_Machine_and_Equipment_Rental</fullName>
                <label>Inside Sales/ Customer Consultant Rental</label>
            </value>
            <value>
                <fullName>Inside_Sales_Customer_Consultant_Rental_Accommodation_Units_RS</fullName>
                <label>Inside Sales/ Customer Consultant RS</label>
            </value>
            <value>
                <fullName>Key_Account_Manager</fullName>
                <label>Key Account Manager</label>
            </value>
            <value>
                <fullName>Key Account Manager Event</fullName>
                <isActive>false</isActive>
                <label>Key Account Manager Event</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlowActionProjectTeamMember.cls
/**
 * SF-1255 Mehrfachanlage von Projektteammitglieder bei PLZ-Änderungen
 * Apex action used in flows Project Territory After Insert Flow and Project After Update Flow to create
 * project team members, avoiding duplicate members and limits
 *
 * @author miriam.ida.tyroller@accenture.com
 * 
 * @version 2023-08-22  miriam.ida.tyroller@accenture.com   creation
 */

public without sharing class FlowActionProjectTeamMember {

    public static final String CLASSNAME = 'FlowActionProjectTeamMember';
    /**
     * InvocableMethod as starting point for each action. Creates project team members based on input project and
     * UserTerritory2Associations, but only if the user isn't already a project team member of the project
     * 
     * @param List<InputVariables> All input variables received from screen flow
     */
    @InvocableMethod(label='Project Team Member Creation' description='Helper method to create project team members ')
    public static void createProjectTeamMembers(List<InputVariables> inputVariables){
        Set<Id> userIds = new Set<Id>();
        List<Core_Error_Log__c> errorLogs = new List<Core_Error_Log__c>();
        List<Project_Team__c> projectTeamMembersToCreate = new List<Project_Team__c>();
        Map<String, Set<Id>> projectTeamMemberListByProjectId = new Map<String, Set<Id>>();

        //only do something if UserTerritory2Association where successfully found
        if(inputVariables.get(0).userTerritoryAssociations?.size() > 0){
            for(UserTerritory2Association usTerrAssoc : inputVariables.get(0).userTerritoryAssociations){
                userIds.add(usTerrAssoc.UserId);
            }

            //query for all Project Team Members with UserIds
            List<Project_Team__c> projectTeamMembers = [SELECT Team_Member__c, Project__c FROM Project_Team__c WHERE Team_Member__c IN: userIds];

            //map Project Team Members by their projects with the related users as a set
            for(Project_Team__c projTeamMember : projectTeamMembers){
                if(projectTeamMemberListByProjectId.keySet().contains(projTeamMember.Project__c)){
                    Set<Id> teamMemberIds = projectTeamMemberListByProjectId.get(projTeamMember.Project__c);
                    teamMemberIds.add(projTeamMember.Team_Member__c);
                    projectTeamMemberListByProjectId.put(projTeamMember.Project__c, teamMemberIds);
                }else{
                    Set<Id> teamMemberIds = new Set<Id>();
                    teamMemberIds.add(projTeamMember.Team_Member__c);
                    projectTeamMemberListByProjectId.put(projTeamMember.Project__c, teamMemberIds);
                }
            }

            //create project team members for input list of UserTerritory2Associations
            for(UserTerritory2Association usTerrAssoc : inputVariables.get(0).userTerritoryAssociations){
                Set<Id> projectTeamMemberIds = projectTeamMemberListByProjectId?.get(inputVariables.get(0).project);
                if(projectTeamMemberIds != null){
                    //only create a project team member if user isn't already linked to project
                    if(!projectTeamMemberIds.contains(usTerrAssoc.UserId)){
                        Project_Team__c projTeamMember = new Project_Team__c();
                        projTeamMember.Project__c = inputVariables.get(0).project;
                        projTeamMember.Team_Member__c = usTerrAssoc.UserId;
                        if(!String.isBlank(usTerrAssoc.RoleInTerritory2)){
                            projTeamMember.Team_Role__c = usTerrAssoc.RoleInTerritory2;
                        }
                        projectTeamMembersToCreate.add(projTeamMember);
                    }
                    else{
                        System.debug('Team Member already exists');
                    }
                }else{
                    Project_Team__c projTeamMember = new Project_Team__c();
                    projTeamMember.Project__c = inputVariables.get(0).project;
                    projTeamMember.Team_Member__c = usTerrAssoc.UserId;
                    if(!String.isBlank(usTerrAssoc.RoleInTerritory2)){
                        projTeamMember.Team_Role__c = usTerrAssoc.RoleInTerritory2;
                    }
                    projectTeamMembersToCreate.add(projTeamMember);
                }
                
            }

            System.debug('########## Project Team Members created: ' + projectTeamMembersToCreate.size());
            System.debug('########## Project Team Members created: ' + projectTeamMembersToCreate);

            if(!projectTeamMembersToCreate.isEmpty()) {
                Database.SaveResult[] ptInsertResult = Database.insert(projectTeamMembersToCreate, false);
                // check results
                Integer i = 0;
                for (Database.SaveResult sr : ptInsertResult) {
                    if (!sr.isSuccess()) {
                        String errorMessage = 'Error while inserting Project_Team__c record with UserId: ' + projectTeamMembersToCreate[i].Team_Member__c + 'for Project: ' + projectTeamMembersToCreate[i].Project__c;
                        String exceptionMessage = sr.getErrors()[0].getStatusCode() + ': ' + sr.getErrors()[0].getMessage();

                        System.debug('########## exceptionMessage: ' + exceptionMessage);
                        errorLogs.add(UTLErrorLog.createErrorLogRecord(CLASSNAME, new HandledException(exceptionMessage), errorMessage, projectTeamMembersToCreate[i].Project__c));
                    }
                    i++;
                }
            }
            
            System.debug('########## errorLogs: ' + errorLogs.size());
            // insert error logs
            UTLErrorLog.insertErrorLogs(errorLogs, CLASSNAME);
        }
    }

    public class InputVariables{
        @InvocableVariable
        public String project; 

        @InvocableVariable
        public List<UserTerritory2Association> userTerritoryAssociations;         
    }
}