force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Core_Apex_Class__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Name of the Apex Class causing the error</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/House_Number_cleaned__c.field-meta.xml
<CustomField>
    <fullName>House_Number_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned House Number data</description>
    <label>House Number (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Street_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Street_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned Street data</description>
    <label>Street (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Salesforce_Project.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Project</fullName>
    <active>true</active>
    <description>Used to create Projects directly in Salesforce.</description>
    <label>Salesforce Project</label>
</RecordType>

force-app/main/default/classes/DUPProjectHandlerTest.cls
/**
 * SF-1205: Test class for DUPProjectHandler
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-26      isabella.moos@accenture.com     creation
 */
@isTest
private with sharing class DUPProjectHandlerTest {
    private static final String SALESFORCE_PROJECT_RECORD_TYPE_NAME = 'Salesforce_Project';
    //private DUPProjectHandler dupProjectHandler = new DUPProjectHandler();

    /**
     * Creates test project, the creation needs to be placed seperately in an TestSetup method to avoid mixed dml operations
     */
    @TestSetup
    private static void createTestData() {
        //create projects
        List<Project__c> testProjectList = TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false);
        testProjectList.addAll(TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false));
        testProjectList.addAll(TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false));
        testProjectList.addAll(TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false));
        insert testProjectList;
    }

    /**
     * Test Project Address change
     * Street name changes or is removed
     * House Number changes or is removed
     */
    @isTest
    private static void testProjectAddressChanges() {
        List<Project__c> testProjectList = [SELECT Id, 
                Project_Address__Street__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c 
            FROM Project__c];
        
        //verify old helper field values
        System.assertEquals('test', testProjectList[0].Street_cleaned__c);
        System.assertEquals('1', testProjectList[0].House_Number_cleaned__c);
        System.assertEquals('test', testProjectList[1].Street_cleaned__c);
        System.assertEquals('1', testProjectList[1].House_Number_cleaned__c);
        System.assertEquals('test', testProjectList[2].Street_cleaned__c);
        System.assertEquals('1', testProjectList[2].House_Number_cleaned__c);
        System.assertEquals('test', testProjectList[3].Street_cleaned__c);
        System.assertEquals('1', testProjectList[3].House_Number_cleaned__c);

        Test.startTest();
            testProjectList[0].Project_Address__Street__s = 'New Street 1';
            testProjectList[1].Project_Address__Street__s = 'New Street 2';
            testProjectList[2].Project_Address__Street__s = null;
            testProjectList[3].Project_Address__Street__s = 'New Street';
            update testProjectList; 
        Test.stopTest();

        List<Project__c> testProjectUpdatedList = [SELECT Id, 
                Project_Address__Street__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c 
            FROM Project__c];

        //verify results
        System.assertEquals('news', testProjectUpdatedList[0].Street_cleaned__c);
        System.assertEquals('1', testProjectUpdatedList[0].House_Number_cleaned__c);
        System.assertEquals('news', testProjectUpdatedList[1].Street_cleaned__c);
        System.assertEquals('2', testProjectUpdatedList[1].House_Number_cleaned__c);
        System.assertEquals(null, testProjectUpdatedList[2].Street_cleaned__c);
        System.assertEquals(null, testProjectUpdatedList[2].House_Number_cleaned__c);
        System.assertEquals('news', testProjectUpdatedList[3].Street_cleaned__c);
        System.assertEquals(null, testProjectUpdatedList[3].House_Number_cleaned__c);
    }

    /**
     * Test Exception
     */
    @isTest
    private static void testException() {
        DUPProjectHandler projectHandler = new DUPProjectHandler();
        projectHandler.testError = true;

        List<Project__c> testProjectBeforeUpdateList = [SELECT Id, 
                Project_Address__Street__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c 
            FROM Project__c 
            LIMIT 1];
        projectHandler.oldProjectsByIds = new Map<Id, Project__c>(testProjectBeforeUpdateList);

        List<Project__c> testProjectAfterUpdateList = [SELECT Id, 
                Project_Address__Street__s, 
                Street_cleaned__c, 
                House_Number_cleaned__c 
            FROM Project__c 
            LIMIT 1];
        testProjectAfterUpdateList[0].Project_Address__Street__s = 'New Street 1';
        Map<Id, Project__c> newProjectsByIds = new Map<Id, Project__c>(testProjectAfterUpdateList);
        projectHandler.newProjectsByIds = newProjectsByIds;

        Test.startTest();
            projectHandler.handleProjectAddressChanges(newProjectsByIds);
        Test.stopTest();

        //verify results
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = : projectHandler.CLASSNAME];
        System.assertEquals(1, errorLogs.size());
    }
}