force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_External_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Core_External_System_Id__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Record ID of the external system</inlineHelpText>
    <label>External System Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GRACE_API_Config__c/GRACE_API_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>GRACE API Config</label>
</CustomObject>

force-app/main/default/objects/GRACE_API_Config__c/fields/Last_Retry_Errors__c.field-meta.xml
<CustomField>
    <fullName>Last_Retry_Errors__c</fullName>
    <description>Last attempt to import the errors again. (Only LOCK Erros at the moment )</description>
    <label>Last Retry Errors</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GRSYAccBatch.cls
/**
 * Batchable to retrieve accounts from Grace and process them in batches 
 * 
 * @author daniel.gette@zeppelin.com
 * 
 * @version 2023-10-04  daniel.gette@zeppelin.com   creation
 */
public with sharing class GRSYAccBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public String query;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('Query executed in Batch' + query);

        GRACE_API_Config__c graceapiConfig = GRACE_API_Config__c.getOrgDefaults();
        graceapiConfig.Last_Retry_Errors__c = Datetime.now();
        update graceapiConfig;
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<SObject> sObjects) {
        List<Core_Error_Log__c> errorLogs = (List<Core_Error_Log__c>) sObjects;
        Set<String> customerNumbers = UTLCommons.filterStringFieldValues(
            errorLogs,
            Core_Error_Log__c.Core_External_System_Id__c
        );

        UTLTriggerHandler.bypass('SHRAccountTriggerHandler');

        System.debug(
            'Following Ids getting passed into batch: ' + String.join((Iterable<String>) customerNumbers, ',')
        );
        new GRSYAccService().processAccountList(customerNumbers);
    }

    public void finish(Database.BatchableContext BC) {
        UTLTriggerHandler.clearBypass('SHRAccountTriggerHandler');
    }
}