force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Lead__c/recordTypes/Account_Lead_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Account_Lead_Record_Type</fullName>
    <active>true</active>
    <description>1. Not integration relevant 2. ZR 3. SF-1155</description>
    <label>Account Lead Record Type</label>
</RecordType>

force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Core_Apex_Class__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Name of the Apex Class causing the error</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Building_Owner__c.field-meta.xml
<CustomField>
    <fullName>Building_Owner__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Filled by Flow &quot;Create Project screen Flow&quot;</description>
    <label>Building Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Building_Owner_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Building_Owner_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned building owner names</description>
    <label>Building Owner (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Involved_Accounts_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Involved_Accounts_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 helper field to store cleaned involved Accounts names</description>
    <label>Involved Accounts (cleaned)</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Salesforce_Project.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Project</fullName>
    <active>true</active>
    <description>Used to create Projects directly in Salesforce.</description>
    <label>Salesforce Project</label>
</RecordType>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Lead__c.field-meta.xml
<CustomField>
    <fullName>Account_Lead__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <referenceTo>Account_Lead__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant
2. ZR
3. SF-1155</description>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZRD
3. SF-1155</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Leads</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Architect</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Bidder</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Building Contractor</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Building Owner</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Consultant</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Further Participants</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>General Constructor</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Operating Firm</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Operator</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Planer</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Planer and Engineers</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Project Controller</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Project Developer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Property Surveillance</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Tenant</label>
    </customValue>
    <masterLabel>Account Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DUPPALRHandlerTest.cls
/**
 * SF-1205: Test class for DUPPALRHandler
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-23      isabella.moos@accenture.com     creation
 */
@IsTest
private with sharing class DUPPALRHandlerTest {
    private static final String ACCOUNT_LEAD_RECORD_TYPE_NAME = 'Account_Lead_Record_Type';
    private static final String SALESFORCE_PROJECT_RECORD_TYPE_NAME = 'Salesforce_Project';

    /**
     * Creates test project, the creation needs to be placed seperately in an TestSetup method to avoid mixed dml operations
     */
    @TestSetup
    private static void createTestData() {
        //create account leads
        List<Account_Lead__c> testAccountLeadList = TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false);
        testAccountLeadList.addAll(TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false));
        testAccountLeadList[1].Name = 'Test Acc 2';
        insert testAccountLeadList;

        //create projects
        List<Project__c> testProjectList = TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false);
        testProjectList.addAll(TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, false));
        testProjectList[1].Name = 'New Project';
        insert testProjectList;

        //create project account lead relations
        List<Project_Account_Lead_Relation__c> testPPALRList = TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '1', testProjectList[0], false);
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '3', testProjectList[0], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[1], '2', testProjectList[0], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '2', testProjectList[1], false));
        insert testPPALRList;
    }

    /**
     * Test Project Account Lead Relation insert
     */
    @isTest
    private static void testInsertPALR() {
        Account_Lead__c accLead = [SELECT Id 
                        FROM Account_Lead__c 
                        WHERE Name LIKE 'ACN%'
                        LIMIT 1];
        Project__c project = [SELECT Id 
                                FROM Project__c 
                                LIMIT 1];

        Test.startTest();
            TESTDataFactory.createTestPALRs(1, accLead, '1', project, true);
        Test.stopTest();

        Project__c updatedProject = [SELECT 
                                        Id, 
                                        Involved_Accounts_cleaned__c,
                                        Building_Owner_cleaned__c,
                                        Building_Owner__c
                                    FROM Project__c 
                                    LIMIT 1];
        String updatedProjectId = updatedProject.id;
        List<Project_Account_Lead_Relation__c> palrList = [SELECT Id 
                                                    FROM Project_Account_Lead_Relation__c 
                                                    WHERE Project__c = :updatedProjectId];

        System.assertEquals(4, palrList.size());
        System.assertEquals('acn,test,acn,', updatedProject.Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', updatedProject.Building_Owner_cleaned__c);
        System.assertEquals('ACN Test Account Lead0', updatedProject.Building_Owner__c);
    }

    /**
     * Test Project Account Lead Relation update of Account Role (Account Lead and Project cannot be reparented)
     */
    @isTest
    private static void testUpdatePAR() {
        Project__c project1 = [SELECT 
                                    Id,
                                    Involved_Accounts_cleaned__c,
                                    Building_Owner_cleaned__c,
                                    Building_Owner__c
                                FROM Project__c 
                                WHERE Name LIKE 'TEST%'
                                LIMIT 1];
        Project__c project2 = [SELECT 
                                    Id,
                                    Involved_Accounts_cleaned__c,
                                    Building_Owner_cleaned__c,
                                    Building_Owner__c
                                FROM Project__c 
                                WHERE Name LIKE 'NEW%'
                                LIMIT 1];

        String project1Id = project1.id;
        String project2Id = project2.id;
        List<Project_Account_Lead_Relation__c> palrList = new List<Project_Account_Lead_Relation__c>();
        List<Project_Account_Lead_Relation__c> palr1 = [SELECT Id
                                                FROM Project_Account_Lead_Relation__c 
                                                WHERE Project__c = :project1Id 
                                                LIMIT 2];
        Project_Account_Lead_Relation__c palr2 = [SELECT Id 
                                            FROM Project_Account_Lead_Relation__c 
                                            WHERE Project__c = :project2Id 
                                            AND Account_Role__c = '2'
                                            LIMIT 1];

        System.assertEquals('acn,test,', project1.Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', project1.Building_Owner_cleaned__c);
        System.assertEquals('acn,', project2.Involved_Accounts_cleaned__c);
        System.assertEquals(null, project2.Building_Owner_cleaned__c);

        Test.startTest();
            palr1[1].Account_Role__c = '1';
            palr1[0].Account_Role__c = '3';
            palr2.Account_Role__c = '3';
            palrList.addAll(palr1);
            palrList.add(palr2);
            update palrList;
        Test.stopTest();

        List<Project__c> updatedProject = [SELECT 
                                        Id, 
                                        Involved_Accounts_cleaned__c,
                                        Building_Owner_cleaned__c 
                                    FROM Project__c 
                                    LIMIT 2];
        String updatedProjectId = updatedProject[0].id;
        List<Project_Account_Lead_Relation__c> updatedPALRList = [SELECT Id 
                                                    FROM Project_Account_Lead_Relation__c];

        System.assertEquals(4, updatedPALRList.size());
        System.assertEquals('test,acn,', updatedProject[0].Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', updatedProject[0].Building_Owner_cleaned__c);
        System.assertEquals(null, updatedProject[1].Involved_Accounts_cleaned__c);
        System.assertEquals('acn,', updatedProject[1].Building_Owner_cleaned__c);
    }

    /**
     * Test Project Account Relation delete
     */
    @isTest
    private static void testDeletePAR() {
        DUPPALRHandler handler = new DUPPALRHandler();

        Project__c project = [SELECT Id 
                                FROM Project__c 
                                WHERE Name LIKE 'TEST%'
                                LIMIT 1];

        String projectId = project.id;
        List<Project_Account_Lead_Relation__c> palrList = [SELECT Id 
                                                    FROM Project_Account_Lead_Relation__c 
                                                    WHERE Project__c = :projectId LIMIT 3];

        Test.startTest();
            delete palrList;
        Test.stopTest();

        Project__c updatedProject = [SELECT 
                                        Id, 
                                        Involved_Accounts_cleaned__c,
                                        Building_Owner_cleaned__c 
                                    FROM Project__c 
                                    WHERE Name LIKE 'TEST%'
                                    LIMIT 1];
        String updatedProjectId = updatedProject.id;
        List<Project_Account_Lead_Relation__c> updatedPALRList = [SELECT Id 
                                                    FROM Project_Account_Lead_Relation__c 
                                                    WHERE Project__c = :updatedProjectId];

        System.assertEquals(0, updatedPALRList.size());
        System.assertEquals(null, updatedProject.Involved_Accounts_cleaned__c);
        System.assertEquals(null, updatedProject.Building_Owner_cleaned__c);
    }

    /**
     * Test Project Account Relation undelete
     */
    @isTest
    private static void testPARException() {
        DUPPALRHandler handler = new DUPPALRHandler();
        Project__c project = [SELECT Id 
                                FROM Project__c 
                                WHERE Name LIKE 'TEST%'
                                LIMIT 1];

        String projectId = project.id;
        List<Project_Account_Lead_Relation__c> palrList = [SELECT Id 
                                                    FROM Project_Account_Lead_Relation__c 
                                                    WHERE Project__c = :projectId LIMIT 3];

        Test.startTest();
            delete palrList;
            undelete palrList;
        Test.stopTest();

        // validate results
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = :handler.CLASSNAME];
        
        System.assertEquals(3, errorLogs.size());
    }
}