force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Lead__c/recordTypes/Account_Lead_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Account_Lead_Record_Type</fullName>
    <active>true</active>
    <description>1. Not integration relevant 2. ZR 3. SF-1155</description>
    <label>Account Lead Record Type</label>
</RecordType>

force-app/main/default/objects/Core_Error_Log__c/Core_Error_Log__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <label>Fehlerlog</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fehlerlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Error_Log__c/fields/Core_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Core_Apex_Class__c</fullName>
    <description>1. Integration relevant (GRACE)
2. Core
3. SF-782</description>
    <inlineHelpText>Name of the Apex Class causing the error</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (Grace)
2. ZR
3. SF-646</description>
    <label>Projekt</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projekte</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Building_Owner_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Building_Owner_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 Helper field to store cleaned building owner names</description>
    <label>Building Owner (cleaned)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Involved_Accounts_cleaned__c.field-meta.xml
<CustomField>
    <fullName>Involved_Accounts_cleaned__c</fullName>
    <description>1. Not integration relevant
2. ZR
3. SF-1205 helper field to store cleaned involved Accounts names</description>
    <label>Involved Accounts (cleaned)</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Salesforce_Project.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Project</fullName>
    <active>true</active>
    <description>Used to create Projects directly in Salesforce.</description>
    <label>Salesforce Project</label>
</RecordType>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Lead__c.field-meta.xml
<CustomField>
    <fullName>Account_Lead__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <referenceTo>Account_Lead__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZRD
3. SF-1155</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Leads</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DUPAccountLeadHandlerTest.cls
/**
 * SF-1205: Test class for DUPAccountLeadHandler
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-24      isabella.moos@accenture.com     creation
 */
@IsTest
private with sharing class DUPAccountLeadHandlerTest {
    private static String ACCOUNT_LEAD_RECORD_TYPE_NAME = 'Account_Lead_Record_Type';
    private static final String SALESFORCE_PROJECT_RECORD_TYPE_NAME = 'Salesforce_Project';

    /**
     * Creates test project, the creation needs to be placed seperately in an TestSetup method to avoid mixed dml operations
     */
    @TestSetup
    private static void createTestData() {
        //create accounts
        List<Account_Lead__c> testAccountLeadList = TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false);
        testAccountLeadList.addAll(TESTDataFactory.createTestAccountLeads(1, ACCOUNT_LEAD_RECORD_TYPE_NAME, false));
        testAccountLeadList[1].Name = 'Test Acc Lead 2';
        insert testAccountLeadList;

        //create projects
        List<Project__c> testProjectList = TESTDataFactory.createTestIBauProjects(1, SALESFORCE_PROJECT_RECORD_TYPE_NAME, true);

        //create project account relations
        List<Project_Account_Lead_Relation__c> testPPALRList = TESTDataFactory.createTestPALRs(1, testAccountLeadList[1], '1', testProjectList[0], false);
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '3', testProjectList[0], false));
        testPPALRList.addAll(TESTDataFactory.createTestPALRs(1, testAccountLeadList[0], '2', testProjectList[0], false));
        insert testPPALRList;
    }

    /**
     * Test success scenario when account name is updated
     */
    @isTest
    private static void testAccountNameUpdate() {
        DUPAccountLeadHandler handler = new DUPAccountLeadHandler();
        Account_Lead__c accLead = [SELECT 
                            Id, 
                            Name 
                        FROM Account_Lead__c 
                        WHERE Name LIKE 'ACN%'
                        LIMIT 1];
        Project__c project = [SELECT 
                        Id, 
                        Building_Owner_cleaned__c, 
                        Involved_Accounts_cleaned__c 
                    FROM Project__c 
                    LIMIT 1];
        
        System.assertEquals('acn,', project.Building_Owner_cleaned__c);
        System.assertEquals('test,acn,', project.Involved_Accounts_cleaned__c);
        
        Test.startTest();
            accLead.Name = 'Updated Account Lead Name';
            update accLead;
        Test.stopTest();

        Project__c updatedProject = [SELECT 
                                        Id, 
                                        Building_Owner_cleaned__c, 
                                        Involved_Accounts_cleaned__c 
                                    FROM Project__c 
                                    LIMIT 1];

        System.assertEquals('updated,', updatedProject.Building_Owner_cleaned__c);
        System.assertEquals('test,updated,', updatedProject.Involved_Accounts_cleaned__c);

        //test if error logs inserted correctly
        List<Core_Error_Log__c> errorLogs = [SELECT Id, Core_Apex_Class__c FROM Core_Error_Log__c WHERE Core_Apex_Class__c = :handler.CLASSNAME];
        System.assertEquals(1, errorLogs.size());
    }
}