force-app/main/default/objects/Account_Lead__c/Account_Lead__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <nameField>
        <label>Account Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/Project_Account_Lead_Relation__c.object-meta.xml
<CustomObject>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Project Account Lead Relation</label>
    <nameField>
        <displayFormat>PALR-{00000000}</displayFormat>
        <label>Project Account Lead Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Account Lead Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Lead__c.field-meta.xml
<CustomField>
    <fullName>Account_Lead__c</fullName>
    <description>1. Integration relevant (ibau, infobau)
2. ZR
3. SF-1155</description>
    <label>Account Lead</label>
    <referenceTo>Account_Lead__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Account_Lead_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Account_Lead_Relation__c/fields/Account_Role__c.field-meta.xml
<CustomField>
    <fullName>Account_Role__c</fullName>
    <description>1. Integration relevant
2. ZR
3. SF-1155</description>
    <label>Account Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Account_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Architect</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Bidder</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Building Contractor</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Building Owner</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Consultant</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>Further Participants</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>General Constructor</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Operating Firm</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Operator</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Planer</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Planer and Engineers</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Project Controller</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Project Developer</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Property Surveillance</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Tenant</label>
    </customValue>
    <masterLabel>Account Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SHRPALRTriggerHandler.cls
/**
 * Handler class detekt changes and routes to the business logic handlers
 * and executes dml operations.
 *
 * @author  isabella.moos@accenture.com
 *
 * @version 2023-10-20  isabella.moos@accenture.com     creation
 */
public with sharing class SHRPALRTriggerHandler extends UTLTriggerHandler  {
    public String CLASSNAME = String.valueOf(this).substring(0, String.valueOf(this).indexOf(':'));

    private DUPPALRHandler palrHandler = new DUPPALRHandler();

    private List<Project_Account_Lead_Relation__c> newPALR;
    private Map<Id, Project_Account_Lead_Relation__c> oldPALRsByIds;
    private Map<Id, Project_Account_Lead_Relation__c> newPALRsByIds;

    Map<Id, Project_Account_Lead_Relation__c> oldPALRMap = new Map<Id, Project_Account_Lead_Relation__c>();
    Map<Id, Project_Account_Lead_Relation__c> newPALRMap = new Map<Id, Project_Account_Lead_Relation__c>();

    public SHRPALRTriggerHandler() {
        this.oldPALRsByIds = (Map<Id, Project_Account_Lead_Relation__c>) Trigger.oldMap;
        this.newPALRsByIds = (Map<Id, Project_Account_Lead_Relation__c>) Trigger.newMap;
    }

    /**
     * Collecting inserted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterInsert
     */
    public override void afterInsert() {
        // Handle record update
        for (Id palrId : this.newPALRsByIds.keySet()) {
            Project_Account_Lead_Relation__c newPALR = this.newPALRsByIds.get(palrId);

            this.newPALRMap.put(newPALR.Id, newPALR);
        }
        // handle if related Account Name change occured
        if (!newPALRMap.isEmpty()) {
            this.palrHandler
                .addNewPALRs(this.newPALRsByIds)
                .executeJob(DUPPALRHandler.JobContext.ON_INSERT);
        }
    }

    /**
     * Collecting changed records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterUpdate
     */
    public override void afterUpdate() {
        // Handle record update
        for (Id palrId : this.newPALRsByIds.keySet()) {
            Project_Account_Lead_Relation__c oldPALR = this.oldPALRsByIds.get(palrId);
            Project_Account_Lead_Relation__c newPALR = this.newPALRsByIds.get(palrId);

            if (oldPALR.Account_Lead__c != newPALR.Account_Lead__c || 
            oldPALR.Account_Role__c != newPALR.Account_Role__c) {
                oldPALRMap.put(oldPALR.Id, oldPALR);
                newPALRMap.put(newPALR.Id, newPALR);
            }
        }
        // handle if related Account Name change occured
        if (! newPALRMap.isEmpty() && 
        ! oldPALRMap.isEmpty()) {
            this.palrHandler
                .addOldPALRs(this.oldPALRsByIds)
                .addNewPALRs(this.newPALRsByIds)
                .executeJob(DUPPALRHandler.JobContext.ON_UPDATE);
        }
    }

    /**
     * Collecting deleted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterDelete
     */
    public override void afterDelete() {
        // Handle record deletion
        for (Id palrId : this.oldPALRsByIds.keySet()) {
            Project_Account_Lead_Relation__c oldPALR = this.oldPALRsByIds.get(palrId);

            this.oldPALRMap.put(oldPALR.Id, oldPALR);
        }
        // handle if related Account Name change occured
        if (! oldPALRMap.isEmpty()) {
            this.palrHandler
                .addOldPALRs(this.oldPALRsByIds)
                .executeJob(DUPPALRHandler.JobContext.ON_DELETE);
        }
    }

    /**
     * Collecting deleted records and handle dml operations.
     *
     * @see UTLTriggerHandler.afterUndelete
     */
    public override void afterUndelete() {
        // Handle record deletion
        for (Id palrId : this.newPALRsByIds.keySet()) {
            Project_Account_Lead_Relation__c newPALR = this.newPALRsByIds.get(palrId);

            this.newPALRMap.put(newPALR.Id, newPALR);
        }
        // handle if related Account Name change occured
        if (! newPALRMap.isEmpty()) {
            this.palrHandler
                .addNewPALRs(this.newPALRsByIds)
                .executeJob(DUPPALRHandler.JobContext.ON_UNDELETE);
        }
    }
}